// One variable per struct under study, so -g emits its full layout.
#include <bgame/bg_local.h>
#include <bgame/bg_public.h>
#include <flame/flame_system.h>
#include <gfx_d3d/r_draw_staticmodel.h>
#include <gfx_d3d/r_material.h>
#include <gfx_d3d/r_rendercmds.h>
#include <gfx_d3d/rb_backend.h>
#include <gfx_d3d/r_dpvs.h>
#include <gfx_d3d/r_dpvs_sceneent.h>
#include <gfx_d3d/r_bsp.h>
#include <gfx_d3d/r_bsp_load_obj.h>
#include <gfx_d3d/r_dobj_skin.h>
#include <gfx_d3d/r_gfx.h>
#include <gfx_d3d/fxprimitives.h>
#include <qcommon/ent.h>
#include <qcommon/graph.h>
#include <qcommon/dvar_cmds.h>
#include <universal/dvar.h>
#include <universal/eval.h>
#include <ui/ui_shared.h>
#include <xanim/dobj.h>
#include <xanim/xmodel.h>
#include <clientscript/cscr_variable.h>
#include <server_mp/sv_snapshot_mp.h>
#include <vehicle/nitrous_vehicle.h>
#include <DynEntity/DynEntity_client.h>

centity_s                    nx_l_centity;
flameGeneric_s               nx_l_flamegeneric;
GfxStaticModelDrawStream     nx_l_gfxsmdrawstream;
LerpEntityStateCreateDynEnt  nx_l_lerpcreatedynent;
LerpEntityState              nx_l_lerpentitystate;
spawner_ent_t                nx_l_spawner;
gentity_s                    nx_l_gentity;
MaterialPass                 nx_l_materialpass;
Material                     nx_l_material;
MaterialTechnique            nx_l_materialtechnique;
dvar_s                       nx_l_dvar;
DvarDumpInfo                 nx_l_dvardumpinfo;
GfxCmdHeader                 nx_l_cmdheader;
GfxCmdStretchPic             nx_l_cmdstretchpic;
GfxCmdDrawText2D             nx_l_cmddrawtext2d;
GfxCmdDrawPoints             nx_l_cmddrawpoints;
GfxCmdDrawLines              nx_l_cmddrawlines;
GfxCmdSetScissor             nx_l_cmdsetscissor;
GfxCmdClearScreen            nx_l_cmdclearscreen;
GfxCmdProjectionSet          nx_l_cmdprojectionset;
DpvsDynamicCellCmd           nx_l_dpvsdyncellcmd;
DpvsEntityCmd                nx_l_dpvsentitycmd;
GfxWorldDpvsPlanes           nx_l_gfxworlddpvsplanes;
Stream2Usage                 nx_l_stream2usage;
GfxModelSkinnedSurface       nx_l_gfxmodelskinnedsurface;
GfxModelRigidSurface         nx_l_gfxmodelrigidsurface;
GfxLightDef                  nx_l_gfxlightdef;
FxEffectDef                  nx_l_fxeffectdef;
XModel                       nx_l_xmodel;
DObj                         nx_l_dobj;
EvalValue                    nx_l_evalvalue;
scrollInfo_s                 nx_l_scrollinfo;
GraphFloat                   nx_l_graphfloat;
VariableStackBuffer          nx_l_variablestackbuffer;
clientSnapshot_t             nx_l_clientsnapshot;
vehicle_info_t               nx_l_vehicleinfo;
DynEntityDef                 nx_l_dynentitydef;
