// layout_gen.h -- generated by tools/ffconv/layout/layout.sh. Do not edit.
//
// Per struct: X_ (x86, as the fastfiles were written) and L_ (LP64, as the
// Switch build lays it out) sizes and member offsets, and the spans of
// pointer-free bytes that copy across unchanged. Members nested in member
// structs are named by path; in arrays of structs, the first element's.
#pragma once
#include <cstdint>

struct LayoutSpan { uint32_t x, l, n; };

// DestructibleStage
enum : uint32_t { X_sizeof_DestructibleStage = 48, L_sizeof_DestructibleStage = 80 };
enum : uint32_t { X_DestructibleStage__showBone = 0, L_DestructibleStage__showBone = 0 };
enum : uint32_t { X_DestructibleStage__breakHealth = 4, L_DestructibleStage__breakHealth = 4 };
enum : uint32_t { X_DestructibleStage__maxTime = 8, L_DestructibleStage__maxTime = 8 };
enum : uint32_t { X_DestructibleStage__flags = 12, L_DestructibleStage__flags = 12 };
enum : uint32_t { X_DestructibleStage__breakEffect = 16, L_DestructibleStage__breakEffect = 16 };
enum : uint32_t { X_DestructibleStage__breakSound = 20, L_DestructibleStage__breakSound = 24 };
enum : uint32_t { X_DestructibleStage__breakNotify = 24, L_DestructibleStage__breakNotify = 32 };
enum : uint32_t { X_DestructibleStage__loopSound = 28, L_DestructibleStage__loopSound = 40 };
enum : uint32_t { X_DestructibleStage__spawnModel = 32, L_DestructibleStage__spawnModel = 48 };
enum : uint32_t { X_DestructibleStage__physPreset = 44, L_DestructibleStage__physPreset = 72 };
static const LayoutSpan SPANS_DestructibleStage[] = {{0,0,2},{4,4,12}};

// DestructiblePiece
enum : uint32_t { X_sizeof_DestructiblePiece = 312, L_sizeof_DestructiblePiece = 496 };
enum : uint32_t { X_DestructiblePiece__stages__showBone = 0, L_DestructiblePiece__stages__showBone = 0 };
enum : uint32_t { X_DestructiblePiece__stages__breakHealth = 4, L_DestructiblePiece__stages__breakHealth = 4 };
enum : uint32_t { X_DestructiblePiece__stages__maxTime = 8, L_DestructiblePiece__stages__maxTime = 8 };
enum : uint32_t { X_DestructiblePiece__stages__flags = 12, L_DestructiblePiece__stages__flags = 12 };
enum : uint32_t { X_DestructiblePiece__stages__breakEffect = 16, L_DestructiblePiece__stages__breakEffect = 16 };
enum : uint32_t { X_DestructiblePiece__stages__breakSound = 20, L_DestructiblePiece__stages__breakSound = 24 };
enum : uint32_t { X_DestructiblePiece__stages__breakNotify = 24, L_DestructiblePiece__stages__breakNotify = 32 };
enum : uint32_t { X_DestructiblePiece__stages__loopSound = 28, L_DestructiblePiece__stages__loopSound = 40 };
enum : uint32_t { X_DestructiblePiece__stages__spawnModel = 32, L_DestructiblePiece__stages__spawnModel = 48 };
enum : uint32_t { X_DestructiblePiece__stages__physPreset = 44, L_DestructiblePiece__stages__physPreset = 72 };
enum : uint32_t { X_DestructiblePiece__parentPiece = 240, L_DestructiblePiece__parentPiece = 400 };
enum : uint32_t { X_DestructiblePiece__parentDamagePercent = 244, L_DestructiblePiece__parentDamagePercent = 404 };
enum : uint32_t { X_DestructiblePiece__bulletDamageScale = 248, L_DestructiblePiece__bulletDamageScale = 408 };
enum : uint32_t { X_DestructiblePiece__explosiveDamageScale = 252, L_DestructiblePiece__explosiveDamageScale = 412 };
enum : uint32_t { X_DestructiblePiece__meleeDamageScale = 256, L_DestructiblePiece__meleeDamageScale = 416 };
enum : uint32_t { X_DestructiblePiece__impactDamageScale = 260, L_DestructiblePiece__impactDamageScale = 420 };
enum : uint32_t { X_DestructiblePiece__entityDamageTransfer = 264, L_DestructiblePiece__entityDamageTransfer = 424 };
enum : uint32_t { X_DestructiblePiece__physConstraints = 268, L_DestructiblePiece__physConstraints = 432 };
enum : uint32_t { X_DestructiblePiece__health = 272, L_DestructiblePiece__health = 440 };
enum : uint32_t { X_DestructiblePiece__damageSound = 276, L_DestructiblePiece__damageSound = 448 };
enum : uint32_t { X_DestructiblePiece__burnEffect = 280, L_DestructiblePiece__burnEffect = 456 };
enum : uint32_t { X_DestructiblePiece__burnSound = 284, L_DestructiblePiece__burnSound = 464 };
enum : uint32_t { X_DestructiblePiece__enableLabel = 288, L_DestructiblePiece__enableLabel = 472 };
enum : uint32_t { X_DestructiblePiece__hideBones = 292, L_DestructiblePiece__hideBones = 476 };
static const LayoutSpan SPANS_DestructiblePiece[] = {{0,0,2},{4,4,12},{48,80,2},{52,84,12},{96,160,2},{100,164,12},{144,240,2},{148,244,12},{192,320,2},{196,324,12},{240,400,1},{244,404,24},{272,440,4},{288,472,2},{292,476,20}};

// DestructibleDef
enum : uint32_t { X_sizeof_DestructibleDef = 24, L_sizeof_DestructibleDef = 48 };
enum : uint32_t { X_DestructibleDef__name = 0, L_DestructibleDef__name = 0 };
enum : uint32_t { X_DestructibleDef__model = 4, L_DestructibleDef__model = 8 };
enum : uint32_t { X_DestructibleDef__pristineModel = 8, L_DestructibleDef__pristineModel = 16 };
enum : uint32_t { X_DestructibleDef__numPieces = 12, L_DestructibleDef__numPieces = 24 };
enum : uint32_t { X_DestructibleDef__pieces = 16, L_DestructibleDef__pieces = 32 };
enum : uint32_t { X_DestructibleDef__clientOnly = 20, L_DestructibleDef__clientOnly = 40 };
static const LayoutSpan SPANS_DestructibleDef[] = {{12,24,4},{20,40,4}};

// ComPrimaryLight
enum : uint32_t { X_sizeof_ComPrimaryLight = 220, L_sizeof_ComPrimaryLight = 224 };
enum : uint32_t { X_ComPrimaryLight__type = 0, L_ComPrimaryLight__type = 0 };
enum : uint32_t { X_ComPrimaryLight__canUseShadowMap = 1, L_ComPrimaryLight__canUseShadowMap = 1 };
enum : uint32_t { X_ComPrimaryLight__exponent = 2, L_ComPrimaryLight__exponent = 2 };
enum : uint32_t { X_ComPrimaryLight__priority = 3, L_ComPrimaryLight__priority = 3 };
enum : uint32_t { X_ComPrimaryLight__cullDist = 4, L_ComPrimaryLight__cullDist = 4 };
enum : uint32_t { X_ComPrimaryLight___pad = 6, L_ComPrimaryLight___pad = 6 };
enum : uint32_t { X_ComPrimaryLight__color = 8, L_ComPrimaryLight__color = 8 };
enum : uint32_t { X_ComPrimaryLight__dir = 20, L_ComPrimaryLight__dir = 20 };
enum : uint32_t { X_ComPrimaryLight__origin = 32, L_ComPrimaryLight__origin = 32 };
enum : uint32_t { X_ComPrimaryLight__radius = 44, L_ComPrimaryLight__radius = 44 };
enum : uint32_t { X_ComPrimaryLight__cosHalfFovOuter = 48, L_ComPrimaryLight__cosHalfFovOuter = 48 };
enum : uint32_t { X_ComPrimaryLight__cosHalfFovInner = 52, L_ComPrimaryLight__cosHalfFovInner = 52 };
enum : uint32_t { X_ComPrimaryLight__cosHalfFovExpanded = 56, L_ComPrimaryLight__cosHalfFovExpanded = 56 };
enum : uint32_t { X_ComPrimaryLight__rotationLimit = 60, L_ComPrimaryLight__rotationLimit = 60 };
enum : uint32_t { X_ComPrimaryLight__translationLimit = 64, L_ComPrimaryLight__translationLimit = 64 };
enum : uint32_t { X_ComPrimaryLight__mipDistance = 68, L_ComPrimaryLight__mipDistance = 68 };
enum : uint32_t { X_ComPrimaryLight__diffuseColor = 72, L_ComPrimaryLight__diffuseColor = 72 };
enum : uint32_t { X_ComPrimaryLight__specularColor = 88, L_ComPrimaryLight__specularColor = 88 };
enum : uint32_t { X_ComPrimaryLight__attenuation = 104, L_ComPrimaryLight__attenuation = 104 };
enum : uint32_t { X_ComPrimaryLight__falloff = 120, L_ComPrimaryLight__falloff = 120 };
enum : uint32_t { X_ComPrimaryLight__angle = 136, L_ComPrimaryLight__angle = 136 };
enum : uint32_t { X_ComPrimaryLight__aAbB = 152, L_ComPrimaryLight__aAbB = 152 };
enum : uint32_t { X_ComPrimaryLight__cookieControl0 = 168, L_ComPrimaryLight__cookieControl0 = 168 };
enum : uint32_t { X_ComPrimaryLight__cookieControl1 = 184, L_ComPrimaryLight__cookieControl1 = 184 };
enum : uint32_t { X_ComPrimaryLight__cookieControl2 = 200, L_ComPrimaryLight__cookieControl2 = 200 };
enum : uint32_t { X_ComPrimaryLight__defName = 216, L_ComPrimaryLight__defName = 216 };
static const LayoutSpan SPANS_ComPrimaryLight[] = {{0,0,216}};

// ComBurnableCell
enum : uint32_t { X_sizeof_ComBurnableCell = 12, L_sizeof_ComBurnableCell = 16 };
enum : uint32_t { X_ComBurnableCell__x = 0, L_ComBurnableCell__x = 0 };
enum : uint32_t { X_ComBurnableCell__y = 4, L_ComBurnableCell__y = 4 };
enum : uint32_t { X_ComBurnableCell__data = 8, L_ComBurnableCell__data = 8 };
static const LayoutSpan SPANS_ComBurnableCell[] = {{0,0,8}};

// ComWorld
enum : uint32_t { X_sizeof_ComWorld = 64, L_sizeof_ComWorld = 88 };
enum : uint32_t { X_ComWorld__name = 0, L_ComWorld__name = 0 };
enum : uint32_t { X_ComWorld__isInUse = 4, L_ComWorld__isInUse = 8 };
enum : uint32_t { X_ComWorld__primaryLightCount = 8, L_ComWorld__primaryLightCount = 12 };
enum : uint32_t { X_ComWorld__primaryLights = 12, L_ComWorld__primaryLights = 16 };
enum : uint32_t { X_ComWorld__waterHeader = 16, L_ComWorld__waterHeader = 24 };
enum : uint32_t { X_ComWorld__numWaterCells = 32, L_ComWorld__numWaterCells = 40 };
enum : uint32_t { X_ComWorld__waterCells = 36, L_ComWorld__waterCells = 48 };
enum : uint32_t { X_ComWorld__burnableHeader = 40, L_ComWorld__burnableHeader = 56 };
enum : uint32_t { X_ComWorld__numBurnableCells = 56, L_ComWorld__numBurnableCells = 72 };
enum : uint32_t { X_ComWorld__burnableCells = 60, L_ComWorld__burnableCells = 80 };
static const LayoutSpan SPANS_ComWorld[] = {{4,8,8},{16,24,20},{40,56,20}};

// GfxWorld
enum : uint32_t { X_sizeof_GfxWorld = 1084, L_sizeof_GfxWorld = 1672 };
enum : uint32_t { X_GfxWorld__name = 0, L_GfxWorld__name = 0 };
enum : uint32_t { X_GfxWorld__baseName = 4, L_GfxWorld__baseName = 8 };
enum : uint32_t { X_GfxWorld__planeCount = 8, L_GfxWorld__planeCount = 16 };
enum : uint32_t { X_GfxWorld__nodeCount = 12, L_GfxWorld__nodeCount = 20 };
enum : uint32_t { X_GfxWorld__surfaceCount = 16, L_GfxWorld__surfaceCount = 24 };
enum : uint32_t { X_GfxWorld__streamInfo__aabbTreeCount = 20, L_GfxWorld__streamInfo__aabbTreeCount = 32 };
enum : uint32_t { X_GfxWorld__streamInfo__aabbTrees = 24, L_GfxWorld__streamInfo__aabbTrees = 40 };
enum : uint32_t { X_GfxWorld__streamInfo__leafRefCount = 28, L_GfxWorld__streamInfo__leafRefCount = 48 };
enum : uint32_t { X_GfxWorld__streamInfo__leafRefs = 32, L_GfxWorld__streamInfo__leafRefs = 56 };
enum : uint32_t { X_GfxWorld__skySurfCount = 36, L_GfxWorld__skySurfCount = 64 };
enum : uint32_t { X_GfxWorld__skyStartSurfs = 40, L_GfxWorld__skyStartSurfs = 72 };
enum : uint32_t { X_GfxWorld__skyImage = 44, L_GfxWorld__skyImage = 80 };
enum : uint32_t { X_GfxWorld__skySamplerState = 48, L_GfxWorld__skySamplerState = 88 };
enum : uint32_t { X_GfxWorld__skyBoxModel = 52, L_GfxWorld__skyBoxModel = 96 };
enum : uint32_t { X_GfxWorld__sunParse = 56, L_GfxWorld__sunParse = 104 };
enum : uint32_t { X_GfxWorld__sunLight = 236, L_GfxWorld__sunLight = 288 };
enum : uint32_t { X_GfxWorld__sunColorFromBsp = 240, L_GfxWorld__sunColorFromBsp = 296 };
enum : uint32_t { X_GfxWorld__sunPrimaryLightIndex = 252, L_GfxWorld__sunPrimaryLightIndex = 308 };
enum : uint32_t { X_GfxWorld__primaryLightCount = 256, L_GfxWorld__primaryLightCount = 312 };
enum : uint32_t { X_GfxWorld__cullGroupCount = 260, L_GfxWorld__cullGroupCount = 316 };
enum : uint32_t { X_GfxWorld__coronaCount = 264, L_GfxWorld__coronaCount = 320 };
enum : uint32_t { X_GfxWorld__coronas = 268, L_GfxWorld__coronas = 328 };
enum : uint32_t { X_GfxWorld__shadowMapVolumeCount = 272, L_GfxWorld__shadowMapVolumeCount = 336 };
enum : uint32_t { X_GfxWorld__shadowMapVolumes = 276, L_GfxWorld__shadowMapVolumes = 344 };
enum : uint32_t { X_GfxWorld__shadowMapVolumePlaneCount = 280, L_GfxWorld__shadowMapVolumePlaneCount = 352 };
enum : uint32_t { X_GfxWorld__shadowMapVolumePlanes = 284, L_GfxWorld__shadowMapVolumePlanes = 360 };
enum : uint32_t { X_GfxWorld__exposureVolumeCount = 288, L_GfxWorld__exposureVolumeCount = 368 };
enum : uint32_t { X_GfxWorld__exposureVolumes = 292, L_GfxWorld__exposureVolumes = 376 };
enum : uint32_t { X_GfxWorld__exposureVolumePlaneCount = 296, L_GfxWorld__exposureVolumePlaneCount = 384 };
enum : uint32_t { X_GfxWorld__exposureVolumePlanes = 300, L_GfxWorld__exposureVolumePlanes = 392 };
enum : uint32_t { X_GfxWorld__skyDynIntensity = 304, L_GfxWorld__skyDynIntensity = 400 };
enum : uint32_t { X_GfxWorld__dpvsPlanes__cellCount = 320, L_GfxWorld__dpvsPlanes__cellCount = 416 };
enum : uint32_t { X_GfxWorld__dpvsPlanes__planes = 324, L_GfxWorld__dpvsPlanes__planes = 424 };
enum : uint32_t { X_GfxWorld__dpvsPlanes__nodes = 328, L_GfxWorld__dpvsPlanes__nodes = 432 };
enum : uint32_t { X_GfxWorld__dpvsPlanes__sceneEntCellBits = 332, L_GfxWorld__dpvsPlanes__sceneEntCellBits = 440 };
enum : uint32_t { X_GfxWorld__cellBitsCount = 336, L_GfxWorld__cellBitsCount = 448 };
enum : uint32_t { X_GfxWorld__cells = 340, L_GfxWorld__cells = 456 };
enum : uint32_t { X_GfxWorld__draw__reflectionProbeCount = 344, L_GfxWorld__draw__reflectionProbeCount = 464 };
enum : uint32_t { X_GfxWorld__draw__reflectionProbes = 348, L_GfxWorld__draw__reflectionProbes = 472 };
enum : uint32_t { X_GfxWorld__draw__reflectionProbeTextures = 352, L_GfxWorld__draw__reflectionProbeTextures = 480 };
enum : uint32_t { X_GfxWorld__draw__lightmapCount = 356, L_GfxWorld__draw__lightmapCount = 488 };
enum : uint32_t { X_GfxWorld__draw__lightmaps = 360, L_GfxWorld__draw__lightmaps = 496 };
enum : uint32_t { X_GfxWorld__draw__lightmapPrimaryTextures = 364, L_GfxWorld__draw__lightmapPrimaryTextures = 504 };
enum : uint32_t { X_GfxWorld__draw__lightmapSecondaryTextures = 368, L_GfxWorld__draw__lightmapSecondaryTextures = 512 };
enum : uint32_t { X_GfxWorld__draw__lightmapSecondaryTexturesB = 372, L_GfxWorld__draw__lightmapSecondaryTexturesB = 520 };
enum : uint32_t { X_GfxWorld__draw__terrainScorchImages = 376, L_GfxWorld__draw__terrainScorchImages = 528 };
enum : uint32_t { X_GfxWorld__draw__vertexCount = 500, L_GfxWorld__draw__vertexCount = 776 };
enum : uint32_t { X_GfxWorld__draw__vd__vertices = 504, L_GfxWorld__draw__vd__vertices = 784 };
enum : uint32_t { X_GfxWorld__draw__vd__worldVb = 508, L_GfxWorld__draw__vd__worldVb = 792 };
enum : uint32_t { X_GfxWorld__draw__vertexLayerDataSize = 512, L_GfxWorld__draw__vertexLayerDataSize = 800 };
enum : uint32_t { X_GfxWorld__draw__vld__data = 516, L_GfxWorld__draw__vld__data = 808 };
enum : uint32_t { X_GfxWorld__draw__vld__layerVb = 520, L_GfxWorld__draw__vld__layerVb = 816 };
enum : uint32_t { X_GfxWorld__draw__vertexStream2DataSize = 524, L_GfxWorld__draw__vertexStream2DataSize = 824 };
enum : uint32_t { X_GfxWorld__draw__indexCount = 528, L_GfxWorld__draw__indexCount = 828 };
enum : uint32_t { X_GfxWorld__draw__indices = 532, L_GfxWorld__draw__indices = 832 };
enum : uint32_t { X_GfxWorld__lightGrid__hasLightRegions = 536, L_GfxWorld__lightGrid__hasLightRegions = 840 };
enum : uint32_t { X_GfxWorld__lightGrid__sunPrimaryLightIndex = 540, L_GfxWorld__lightGrid__sunPrimaryLightIndex = 844 };
enum : uint32_t { X_GfxWorld__lightGrid__mins = 544, L_GfxWorld__lightGrid__mins = 848 };
enum : uint32_t { X_GfxWorld__lightGrid__maxs = 550, L_GfxWorld__lightGrid__maxs = 854 };
enum : uint32_t { X_GfxWorld__lightGrid__rowAxis = 556, L_GfxWorld__lightGrid__rowAxis = 860 };
enum : uint32_t { X_GfxWorld__lightGrid__colAxis = 560, L_GfxWorld__lightGrid__colAxis = 864 };
enum : uint32_t { X_GfxWorld__lightGrid__rowDataStart = 564, L_GfxWorld__lightGrid__rowDataStart = 872 };
enum : uint32_t { X_GfxWorld__lightGrid__rawRowDataSize = 568, L_GfxWorld__lightGrid__rawRowDataSize = 880 };
enum : uint32_t { X_GfxWorld__lightGrid__rawRowData = 572, L_GfxWorld__lightGrid__rawRowData = 888 };
enum : uint32_t { X_GfxWorld__lightGrid__entryCount = 576, L_GfxWorld__lightGrid__entryCount = 896 };
enum : uint32_t { X_GfxWorld__lightGrid__entries = 580, L_GfxWorld__lightGrid__entries = 904 };
enum : uint32_t { X_GfxWorld__lightGrid__colorCount = 584, L_GfxWorld__lightGrid__colorCount = 912 };
enum : uint32_t { X_GfxWorld__lightGrid__colors = 588, L_GfxWorld__lightGrid__colors = 920 };
enum : uint32_t { X_GfxWorld__modelCount = 592, L_GfxWorld__modelCount = 928 };
enum : uint32_t { X_GfxWorld__models = 596, L_GfxWorld__models = 936 };
enum : uint32_t { X_GfxWorld__mins = 600, L_GfxWorld__mins = 944 };
enum : uint32_t { X_GfxWorld__maxs = 612, L_GfxWorld__maxs = 956 };
enum : uint32_t { X_GfxWorld__checksum = 624, L_GfxWorld__checksum = 968 };
enum : uint32_t { X_GfxWorld__materialMemoryCount = 628, L_GfxWorld__materialMemoryCount = 972 };
enum : uint32_t { X_GfxWorld__materialMemory = 632, L_GfxWorld__materialMemory = 976 };
enum : uint32_t { X_GfxWorld__sun__hasValidData = 636, L_GfxWorld__sun__hasValidData = 984 };
enum : uint32_t { X_GfxWorld__sun__spriteMaterial = 640, L_GfxWorld__sun__spriteMaterial = 992 };
enum : uint32_t { X_GfxWorld__sun__flareMaterial = 644, L_GfxWorld__sun__flareMaterial = 1000 };
enum : uint32_t { X_GfxWorld__sun__spriteSize = 648, L_GfxWorld__sun__spriteSize = 1008 };
enum : uint32_t { X_GfxWorld__sun__flareMinSize = 652, L_GfxWorld__sun__flareMinSize = 1012 };
enum : uint32_t { X_GfxWorld__sun__flareMinDot = 656, L_GfxWorld__sun__flareMinDot = 1016 };
enum : uint32_t { X_GfxWorld__sun__flareMaxSize = 660, L_GfxWorld__sun__flareMaxSize = 1020 };
enum : uint32_t { X_GfxWorld__sun__flareMaxDot = 664, L_GfxWorld__sun__flareMaxDot = 1024 };
enum : uint32_t { X_GfxWorld__sun__flareMaxAlpha = 668, L_GfxWorld__sun__flareMaxAlpha = 1028 };
enum : uint32_t { X_GfxWorld__sun__flareFadeInTime = 672, L_GfxWorld__sun__flareFadeInTime = 1032 };
enum : uint32_t { X_GfxWorld__sun__flareFadeOutTime = 676, L_GfxWorld__sun__flareFadeOutTime = 1036 };
enum : uint32_t { X_GfxWorld__sun__blindMinDot = 680, L_GfxWorld__sun__blindMinDot = 1040 };
enum : uint32_t { X_GfxWorld__sun__blindMaxDot = 684, L_GfxWorld__sun__blindMaxDot = 1044 };
enum : uint32_t { X_GfxWorld__sun__blindMaxDarken = 688, L_GfxWorld__sun__blindMaxDarken = 1048 };
enum : uint32_t { X_GfxWorld__sun__blindFadeInTime = 692, L_GfxWorld__sun__blindFadeInTime = 1052 };
enum : uint32_t { X_GfxWorld__sun__blindFadeOutTime = 696, L_GfxWorld__sun__blindFadeOutTime = 1056 };
enum : uint32_t { X_GfxWorld__sun__glareMinDot = 700, L_GfxWorld__sun__glareMinDot = 1060 };
enum : uint32_t { X_GfxWorld__sun__glareMaxDot = 704, L_GfxWorld__sun__glareMaxDot = 1064 };
enum : uint32_t { X_GfxWorld__sun__glareMaxLighten = 708, L_GfxWorld__sun__glareMaxLighten = 1068 };
enum : uint32_t { X_GfxWorld__sun__glareFadeInTime = 712, L_GfxWorld__sun__glareFadeInTime = 1072 };
enum : uint32_t { X_GfxWorld__sun__glareFadeOutTime = 716, L_GfxWorld__sun__glareFadeOutTime = 1076 };
enum : uint32_t { X_GfxWorld__sun__sunFxPosition = 720, L_GfxWorld__sun__sunFxPosition = 1080 };
enum : uint32_t { X_GfxWorld__outdoorLookupMatrix = 732, L_GfxWorld__outdoorLookupMatrix = 1096 };
enum : uint32_t { X_GfxWorld__outdoorImage = 796, L_GfxWorld__outdoorImage = 1160 };
enum : uint32_t { X_GfxWorld__cellCasterBits = 800, L_GfxWorld__cellCasterBits = 1168 };
enum : uint32_t { X_GfxWorld__sceneDynModel = 804, L_GfxWorld__sceneDynModel = 1176 };
enum : uint32_t { X_GfxWorld__sceneDynBrush = 808, L_GfxWorld__sceneDynBrush = 1184 };
enum : uint32_t { X_GfxWorld__primaryLightEntityShadowVis = 812, L_GfxWorld__primaryLightEntityShadowVis = 1192 };
enum : uint32_t { X_GfxWorld__primaryLightDynEntShadowVis = 816, L_GfxWorld__primaryLightDynEntShadowVis = 1200 };
enum : uint32_t { X_GfxWorld__nonSunPrimaryLightForModelDynEnt = 824, L_GfxWorld__nonSunPrimaryLightForModelDynEnt = 1216 };
enum : uint32_t { X_GfxWorld__shadowGeom = 828, L_GfxWorld__shadowGeom = 1224 };
enum : uint32_t { X_GfxWorld__lightRegion = 832, L_GfxWorld__lightRegion = 1232 };
enum : uint32_t { X_GfxWorld__dpvs__smodelCount = 836, L_GfxWorld__dpvs__smodelCount = 1240 };
enum : uint32_t { X_GfxWorld__dpvs__dynamicSModelCount = 840, L_GfxWorld__dpvs__dynamicSModelCount = 1244 };
enum : uint32_t { X_GfxWorld__dpvs__staticSurfaceCount = 844, L_GfxWorld__dpvs__staticSurfaceCount = 1248 };
enum : uint32_t { X_GfxWorld__dpvs__litSurfsBegin = 848, L_GfxWorld__dpvs__litSurfsBegin = 1252 };
enum : uint32_t { X_GfxWorld__dpvs__litSurfsEnd = 852, L_GfxWorld__dpvs__litSurfsEnd = 1256 };
enum : uint32_t { X_GfxWorld__dpvs__decalSurfsBegin = 856, L_GfxWorld__dpvs__decalSurfsBegin = 1260 };
enum : uint32_t { X_GfxWorld__dpvs__decalSurfsEnd = 860, L_GfxWorld__dpvs__decalSurfsEnd = 1264 };
enum : uint32_t { X_GfxWorld__dpvs__emissiveSurfsBegin = 864, L_GfxWorld__dpvs__emissiveSurfsBegin = 1268 };
enum : uint32_t { X_GfxWorld__dpvs__emissiveSurfsEnd = 868, L_GfxWorld__dpvs__emissiveSurfsEnd = 1272 };
enum : uint32_t { X_GfxWorld__dpvs__smodelVisDataCount = 872, L_GfxWorld__dpvs__smodelVisDataCount = 1276 };
enum : uint32_t { X_GfxWorld__dpvs__surfaceVisDataCount = 876, L_GfxWorld__dpvs__surfaceVisDataCount = 1280 };
enum : uint32_t { X_GfxWorld__dpvs__smodelVisData = 880, L_GfxWorld__dpvs__smodelVisData = 1288 };
enum : uint32_t { X_GfxWorld__dpvs__surfaceVisData = 892, L_GfxWorld__dpvs__surfaceVisData = 1312 };
enum : uint32_t { X_GfxWorld__dpvs__smodelVisDataCameraSaved = 904, L_GfxWorld__dpvs__smodelVisDataCameraSaved = 1336 };
enum : uint32_t { X_GfxWorld__dpvs__surfaceVisDataCameraSaved = 908, L_GfxWorld__dpvs__surfaceVisDataCameraSaved = 1344 };
enum : uint32_t { X_GfxWorld__dpvs__lodData = 912, L_GfxWorld__dpvs__lodData = 1352 };
enum : uint32_t { X_GfxWorld__dpvs__sortedSurfIndex = 916, L_GfxWorld__dpvs__sortedSurfIndex = 1360 };
enum : uint32_t { X_GfxWorld__dpvs__smodelInsts = 920, L_GfxWorld__dpvs__smodelInsts = 1368 };
enum : uint32_t { X_GfxWorld__dpvs__surfaces = 924, L_GfxWorld__dpvs__surfaces = 1376 };
enum : uint32_t { X_GfxWorld__dpvs__cullGroups = 928, L_GfxWorld__dpvs__cullGroups = 1384 };
enum : uint32_t { X_GfxWorld__dpvs__smodelDrawInsts = 932, L_GfxWorld__dpvs__smodelDrawInsts = 1392 };
enum : uint32_t { X_GfxWorld__dpvs__surfaceMaterials = 936, L_GfxWorld__dpvs__surfaceMaterials = 1400 };
enum : uint32_t { X_GfxWorld__dpvs__surfaceCastsSunShadow = 940, L_GfxWorld__dpvs__surfaceCastsSunShadow = 1408 };
enum : uint32_t { X_GfxWorld__dpvs__usageCount = 944, L_GfxWorld__dpvs__usageCount = 1416 };
enum : uint32_t { X_GfxWorld__dpvsDyn__dynEntClientWordCount = 948, L_GfxWorld__dpvsDyn__dynEntClientWordCount = 1424 };
enum : uint32_t { X_GfxWorld__dpvsDyn__dynEntClientCount = 956, L_GfxWorld__dpvsDyn__dynEntClientCount = 1432 };
enum : uint32_t { X_GfxWorld__dpvsDyn__dynEntCellBits = 964, L_GfxWorld__dpvsDyn__dynEntCellBits = 1440 };
enum : uint32_t { X_GfxWorld__dpvsDyn__dynEntVisData = 972, L_GfxWorld__dpvsDyn__dynEntVisData = 1456 };
enum : uint32_t { X_GfxWorld__worldLodChainCount = 996, L_GfxWorld__worldLodChainCount = 1504 };
enum : uint32_t { X_GfxWorld__worldLodChains = 1000, L_GfxWorld__worldLodChains = 1512 };
enum : uint32_t { X_GfxWorld__worldLodInfoCount = 1004, L_GfxWorld__worldLodInfoCount = 1520 };
enum : uint32_t { X_GfxWorld__worldLodInfos = 1008, L_GfxWorld__worldLodInfos = 1528 };
enum : uint32_t { X_GfxWorld__worldLodSurfaceCount = 1012, L_GfxWorld__worldLodSurfaceCount = 1536 };
enum : uint32_t { X_GfxWorld__worldLodSurfaces = 1016, L_GfxWorld__worldLodSurfaces = 1544 };
enum : uint32_t { X_GfxWorld__waterDirection = 1020, L_GfxWorld__waterDirection = 1552 };
enum : uint32_t { X_GfxWorld__waterBuffers__bufferSize = 1024, L_GfxWorld__waterBuffers__bufferSize = 1560 };
enum : uint32_t { X_GfxWorld__waterBuffers__buffer = 1028, L_GfxWorld__waterBuffers__buffer = 1568 };
enum : uint32_t { X_GfxWorld__waterMaterial = 1040, L_GfxWorld__waterMaterial = 1592 };
enum : uint32_t { X_GfxWorld__coronaMaterial = 1044, L_GfxWorld__coronaMaterial = 1600 };
enum : uint32_t { X_GfxWorld__ropeMaterial = 1048, L_GfxWorld__ropeMaterial = 1608 };
enum : uint32_t { X_GfxWorld__numOccluders = 1052, L_GfxWorld__numOccluders = 1616 };
enum : uint32_t { X_GfxWorld__occluders = 1056, L_GfxWorld__occluders = 1624 };
enum : uint32_t { X_GfxWorld__numOutdoorBounds = 1060, L_GfxWorld__numOutdoorBounds = 1632 };
enum : uint32_t { X_GfxWorld__outdoorBounds = 1064, L_GfxWorld__outdoorBounds = 1640 };
enum : uint32_t { X_GfxWorld__heroLightCount = 1068, L_GfxWorld__heroLightCount = 1648 };
enum : uint32_t { X_GfxWorld__heroLightTreeCount = 1072, L_GfxWorld__heroLightTreeCount = 1652 };
enum : uint32_t { X_GfxWorld__heroLights = 1076, L_GfxWorld__heroLights = 1656 };
enum : uint32_t { X_GfxWorld__heroLightTree = 1080, L_GfxWorld__heroLightTree = 1664 };
static const LayoutSpan SPANS_GfxWorld[] = {{8,16,12},{20,32,4},{28,48,4},{36,64,4},{48,88,1},{56,104,180},{240,296,28},{272,336,4},{280,352,4},{288,368,4},{296,384,4},{304,400,20},{336,448,4},{344,464,4},{356,488,4},{500,776,4},{512,800,4},{524,824,8},{536,840,1},{540,844,24},{568,880,4},{576,896,4},{584,912,4},{592,928,4},{600,944,32},{636,984,1},{648,1008,84},{732,1096,64},{836,1240,44},{944,1416,4},{948,1424,16},{996,1504,4},{1004,1520,4},{1012,1536,4},{1020,1552,4},{1024,1560,4},{1032,1576,4},{1052,1616,4},{1060,1632,4},{1068,1648,8}};

// GfxWorldStreamInfo
enum : uint32_t { X_sizeof_GfxWorldStreamInfo = 16, L_sizeof_GfxWorldStreamInfo = 32 };
enum : uint32_t { X_GfxWorldStreamInfo__aabbTreeCount = 0, L_GfxWorldStreamInfo__aabbTreeCount = 0 };
enum : uint32_t { X_GfxWorldStreamInfo__aabbTrees = 4, L_GfxWorldStreamInfo__aabbTrees = 8 };
enum : uint32_t { X_GfxWorldStreamInfo__leafRefCount = 8, L_GfxWorldStreamInfo__leafRefCount = 16 };
enum : uint32_t { X_GfxWorldStreamInfo__leafRefs = 12, L_GfxWorldStreamInfo__leafRefs = 24 };
static const LayoutSpan SPANS_GfxWorldStreamInfo[] = {{0,0,4},{8,16,4}};

// GfxStreamingAabbTree
enum : uint32_t { X_sizeof_GfxStreamingAabbTree = 32, L_sizeof_GfxStreamingAabbTree = 32 };
enum : uint32_t { X_GfxStreamingAabbTree__firstItem = 0, L_GfxStreamingAabbTree__firstItem = 0 };
enum : uint32_t { X_GfxStreamingAabbTree__itemCount = 2, L_GfxStreamingAabbTree__itemCount = 2 };
enum : uint32_t { X_GfxStreamingAabbTree__firstChild = 4, L_GfxStreamingAabbTree__firstChild = 4 };
enum : uint32_t { X_GfxStreamingAabbTree__childCount = 6, L_GfxStreamingAabbTree__childCount = 6 };
enum : uint32_t { X_GfxStreamingAabbTree__mins = 8, L_GfxStreamingAabbTree__mins = 8 };
enum : uint32_t { X_GfxStreamingAabbTree__maxs = 20, L_GfxStreamingAabbTree__maxs = 20 };
static const LayoutSpan SPANS_GfxStreamingAabbTree[] = {{0,0,32}};

// GfxLight
enum : uint32_t { X_sizeof_GfxLight = 368, L_sizeof_GfxLight = 368 };
enum : uint32_t { X_GfxLight__type = 0, L_GfxLight__type = 0 };
enum : uint32_t { X_GfxLight__canUseShadowMap = 1, L_GfxLight__canUseShadowMap = 1 };
enum : uint32_t { X_GfxLight__cullDist = 2, L_GfxLight__cullDist = 2 };
enum : uint32_t { X_GfxLight__color = 4, L_GfxLight__color = 4 };
enum : uint32_t { X_GfxLight__dir = 16, L_GfxLight__dir = 16 };
enum : uint32_t { X_GfxLight__origin = 28, L_GfxLight__origin = 28 };
enum : uint32_t { X_GfxLight__radius = 40, L_GfxLight__radius = 40 };
enum : uint32_t { X_GfxLight__cosHalfFovOuter = 44, L_GfxLight__cosHalfFovOuter = 44 };
enum : uint32_t { X_GfxLight__cosHalfFovInner = 48, L_GfxLight__cosHalfFovInner = 48 };
enum : uint32_t { X_GfxLight__exponent = 52, L_GfxLight__exponent = 52 };
enum : uint32_t { X_GfxLight__spotShadowIndex = 56, L_GfxLight__spotShadowIndex = 56 };
enum : uint32_t { X_GfxLight__angles = 60, L_GfxLight__angles = 60 };
enum : uint32_t { X_GfxLight__spotShadowHiDistance = 72, L_GfxLight__spotShadowHiDistance = 72 };
enum : uint32_t { X_GfxLight__diffuseColor = 76, L_GfxLight__diffuseColor = 76 };
enum : uint32_t { X_GfxLight__specularColor = 92, L_GfxLight__specularColor = 92 };
enum : uint32_t { X_GfxLight__shadowColor = 108, L_GfxLight__shadowColor = 108 };
enum : uint32_t { X_GfxLight__falloff = 124, L_GfxLight__falloff = 124 };
enum : uint32_t { X_GfxLight__attenuation = 140, L_GfxLight__attenuation = 140 };
enum : uint32_t { X_GfxLight__aAbB = 156, L_GfxLight__aAbB = 156 };
enum : uint32_t { X_GfxLight__cookieControl0 = 172, L_GfxLight__cookieControl0 = 172 };
enum : uint32_t { X_GfxLight__cookieControl1 = 188, L_GfxLight__cookieControl1 = 188 };
enum : uint32_t { X_GfxLight__cookieControl2 = 204, L_GfxLight__cookieControl2 = 204 };
enum : uint32_t { X_GfxLight__viewMatrix = 224, L_GfxLight__viewMatrix = 224 };
enum : uint32_t { X_GfxLight__projMatrix = 288, L_GfxLight__projMatrix = 288 };
enum : uint32_t { X_GfxLight__def = 352, L_GfxLight__def = 352 };
static const LayoutSpan SPANS_GfxLight[] = {{0,0,220},{224,224,128}};

// GfxLightCorona
enum : uint32_t { X_sizeof_GfxLightCorona = 32, L_sizeof_GfxLightCorona = 32 };
enum : uint32_t { X_GfxLightCorona__origin = 0, L_GfxLightCorona__origin = 0 };
enum : uint32_t { X_GfxLightCorona__radius = 12, L_GfxLightCorona__radius = 12 };
enum : uint32_t { X_GfxLightCorona__color = 16, L_GfxLightCorona__color = 16 };
enum : uint32_t { X_GfxLightCorona__intensity = 28, L_GfxLightCorona__intensity = 28 };
static const LayoutSpan SPANS_GfxLightCorona[] = {{0,0,32}};

// GfxShadowMapVolume
enum : uint32_t { X_sizeof_GfxShadowMapVolume = 16, L_sizeof_GfxShadowMapVolume = 16 };
enum : uint32_t { X_GfxShadowMapVolume__control = 0, L_GfxShadowMapVolume__control = 0 };
enum : uint32_t { X_GfxShadowMapVolume__padding1 = 4, L_GfxShadowMapVolume__padding1 = 4 };
enum : uint32_t { X_GfxShadowMapVolume__padding2 = 8, L_GfxShadowMapVolume__padding2 = 8 };
enum : uint32_t { X_GfxShadowMapVolume__padding3 = 12, L_GfxShadowMapVolume__padding3 = 12 };
static const LayoutSpan SPANS_GfxShadowMapVolume[] = {{0,0,16}};

// GfxVolumePlane
enum : uint32_t { X_sizeof_GfxVolumePlane = 16, L_sizeof_GfxVolumePlane = 16 };
enum : uint32_t { X_GfxVolumePlane__plane = 0, L_GfxVolumePlane__plane = 0 };
static const LayoutSpan SPANS_GfxVolumePlane[] = {{0,0,16}};

// GfxExposureVolume
enum : uint32_t { X_sizeof_GfxExposureVolume = 24, L_sizeof_GfxExposureVolume = 24 };
enum : uint32_t { X_GfxExposureVolume__control = 0, L_GfxExposureVolume__control = 0 };
enum : uint32_t { X_GfxExposureVolume__exposure = 4, L_GfxExposureVolume__exposure = 4 };
enum : uint32_t { X_GfxExposureVolume__luminanceIncreaseScale = 8, L_GfxExposureVolume__luminanceIncreaseScale = 8 };
enum : uint32_t { X_GfxExposureVolume__luminanceDecreaseScale = 12, L_GfxExposureVolume__luminanceDecreaseScale = 12 };
enum : uint32_t { X_GfxExposureVolume__featherRange = 16, L_GfxExposureVolume__featherRange = 16 };
enum : uint32_t { X_GfxExposureVolume__featherAdjust = 20, L_GfxExposureVolume__featherAdjust = 20 };
static const LayoutSpan SPANS_GfxExposureVolume[] = {{0,0,24}};

// GfxWorldDpvsPlanes
enum : uint32_t { X_sizeof_GfxWorldDpvsPlanes = 16, L_sizeof_GfxWorldDpvsPlanes = 32 };
enum : uint32_t { X_GfxWorldDpvsPlanes__cellCount = 0, L_GfxWorldDpvsPlanes__cellCount = 0 };
enum : uint32_t { X_GfxWorldDpvsPlanes__planes = 4, L_GfxWorldDpvsPlanes__planes = 8 };
enum : uint32_t { X_GfxWorldDpvsPlanes__nodes = 8, L_GfxWorldDpvsPlanes__nodes = 16 };
enum : uint32_t { X_GfxWorldDpvsPlanes__sceneEntCellBits = 12, L_GfxWorldDpvsPlanes__sceneEntCellBits = 24 };
static const LayoutSpan SPANS_GfxWorldDpvsPlanes[] = {{0,0,4}};

// cplane_s
enum : uint32_t { X_sizeof_cplane_s = 20, L_sizeof_cplane_s = 20 };
enum : uint32_t { X_cplane_s__normal = 0, L_cplane_s__normal = 0 };
enum : uint32_t { X_cplane_s__dist = 12, L_cplane_s__dist = 12 };
enum : uint32_t { X_cplane_s__type = 16, L_cplane_s__type = 16 };
enum : uint32_t { X_cplane_s__signbits = 17, L_cplane_s__signbits = 17 };
enum : uint32_t { X_cplane_s__pad = 18, L_cplane_s__pad = 18 };
static const LayoutSpan SPANS_cplane_s[] = {{0,0,20}};

// GfxCell
enum : uint32_t { X_sizeof_GfxCell = 56, L_sizeof_GfxCell = 88 };
enum : uint32_t { X_GfxCell__mins = 0, L_GfxCell__mins = 0 };
enum : uint32_t { X_GfxCell__maxs = 12, L_GfxCell__maxs = 12 };
enum : uint32_t { X_GfxCell__aabbTreeCount = 24, L_GfxCell__aabbTreeCount = 24 };
enum : uint32_t { X_GfxCell__aabbTree = 28, L_GfxCell__aabbTree = 32 };
enum : uint32_t { X_GfxCell__portalCount = 32, L_GfxCell__portalCount = 40 };
enum : uint32_t { X_GfxCell__portals = 36, L_GfxCell__portals = 48 };
enum : uint32_t { X_GfxCell__cullGroupCount = 40, L_GfxCell__cullGroupCount = 56 };
enum : uint32_t { X_GfxCell__cullGroups = 44, L_GfxCell__cullGroups = 64 };
enum : uint32_t { X_GfxCell__reflectionProbeCount = 48, L_GfxCell__reflectionProbeCount = 72 };
enum : uint32_t { X_GfxCell__reflectionProbes = 52, L_GfxCell__reflectionProbes = 80 };
static const LayoutSpan SPANS_GfxCell[] = {{0,0,28},{32,40,4},{40,56,4},{48,72,1}};

// GfxAabbTree
enum : uint32_t { X_sizeof_GfxAabbTree = 40, L_sizeof_GfxAabbTree = 48 };
enum : uint32_t { X_GfxAabbTree__mins = 0, L_GfxAabbTree__mins = 0 };
enum : uint32_t { X_GfxAabbTree__maxs = 12, L_GfxAabbTree__maxs = 12 };
enum : uint32_t { X_GfxAabbTree__childCount = 24, L_GfxAabbTree__childCount = 24 };
enum : uint32_t { X_GfxAabbTree__surfaceCount = 26, L_GfxAabbTree__surfaceCount = 26 };
enum : uint32_t { X_GfxAabbTree__startSurfIndex = 28, L_GfxAabbTree__startSurfIndex = 28 };
enum : uint32_t { X_GfxAabbTree__smodelIndexCount = 30, L_GfxAabbTree__smodelIndexCount = 30 };
enum : uint32_t { X_GfxAabbTree__smodelIndexes = 32, L_GfxAabbTree__smodelIndexes = 32 };
enum : uint32_t { X_GfxAabbTree__childrenOffset = 36, L_GfxAabbTree__childrenOffset = 40 };
static const LayoutSpan SPANS_GfxAabbTree[] = {{0,0,32},{36,40,4}};

// GfxPortal
enum : uint32_t { X_sizeof_GfxPortal = 68, L_sizeof_GfxPortal = 96 };
enum : uint32_t { X_GfxPortal__writable__isQueued = 0, L_GfxPortal__writable__isQueued = 0 };
enum : uint32_t { X_GfxPortal__writable__isAncestor = 1, L_GfxPortal__writable__isAncestor = 1 };
enum : uint32_t { X_GfxPortal__writable__recursionDepth = 2, L_GfxPortal__writable__recursionDepth = 2 };
enum : uint32_t { X_GfxPortal__writable__hullPointCount = 3, L_GfxPortal__writable__hullPointCount = 3 };
enum : uint32_t { X_GfxPortal__writable__hullPoints = 4, L_GfxPortal__writable__hullPoints = 8 };
enum : uint32_t { X_GfxPortal__writable__queuedParent = 8, L_GfxPortal__writable__queuedParent = 16 };
enum : uint32_t { X_GfxPortal__plane = 12, L_GfxPortal__plane = 24 };
enum : uint32_t { X_GfxPortal__cell = 32, L_GfxPortal__cell = 48 };
enum : uint32_t { X_GfxPortal__vertices = 36, L_GfxPortal__vertices = 56 };
enum : uint32_t { X_GfxPortal__vertexCount = 40, L_GfxPortal__vertexCount = 64 };
enum : uint32_t { X_GfxPortal__hullAxis = 44, L_GfxPortal__hullAxis = 68 };
static const LayoutSpan SPANS_GfxPortal[] = {{0,0,4},{12,24,20},{40,64,1},{44,68,24}};

// GfxPortalWritable
enum : uint32_t { X_sizeof_GfxPortalWritable = 12, L_sizeof_GfxPortalWritable = 24 };
enum : uint32_t { X_GfxPortalWritable__isQueued = 0, L_GfxPortalWritable__isQueued = 0 };
enum : uint32_t { X_GfxPortalWritable__isAncestor = 1, L_GfxPortalWritable__isAncestor = 1 };
enum : uint32_t { X_GfxPortalWritable__recursionDepth = 2, L_GfxPortalWritable__recursionDepth = 2 };
enum : uint32_t { X_GfxPortalWritable__hullPointCount = 3, L_GfxPortalWritable__hullPointCount = 3 };
enum : uint32_t { X_GfxPortalWritable__hullPoints = 4, L_GfxPortalWritable__hullPoints = 8 };
enum : uint32_t { X_GfxPortalWritable__queuedParent = 8, L_GfxPortalWritable__queuedParent = 16 };
static const LayoutSpan SPANS_GfxPortalWritable[] = {{0,0,4}};

// GfxWorldDraw
enum : uint32_t { X_sizeof_GfxWorldDraw = 192, L_sizeof_GfxWorldDraw = 376 };
enum : uint32_t { X_GfxWorldDraw__reflectionProbeCount = 0, L_GfxWorldDraw__reflectionProbeCount = 0 };
enum : uint32_t { X_GfxWorldDraw__reflectionProbes = 4, L_GfxWorldDraw__reflectionProbes = 8 };
enum : uint32_t { X_GfxWorldDraw__reflectionProbeTextures = 8, L_GfxWorldDraw__reflectionProbeTextures = 16 };
enum : uint32_t { X_GfxWorldDraw__lightmapCount = 12, L_GfxWorldDraw__lightmapCount = 24 };
enum : uint32_t { X_GfxWorldDraw__lightmaps = 16, L_GfxWorldDraw__lightmaps = 32 };
enum : uint32_t { X_GfxWorldDraw__lightmapPrimaryTextures = 20, L_GfxWorldDraw__lightmapPrimaryTextures = 40 };
enum : uint32_t { X_GfxWorldDraw__lightmapSecondaryTextures = 24, L_GfxWorldDraw__lightmapSecondaryTextures = 48 };
enum : uint32_t { X_GfxWorldDraw__lightmapSecondaryTexturesB = 28, L_GfxWorldDraw__lightmapSecondaryTexturesB = 56 };
enum : uint32_t { X_GfxWorldDraw__terrainScorchImages = 32, L_GfxWorldDraw__terrainScorchImages = 64 };
enum : uint32_t { X_GfxWorldDraw__vertexCount = 156, L_GfxWorldDraw__vertexCount = 312 };
enum : uint32_t { X_GfxWorldDraw__vd__vertices = 160, L_GfxWorldDraw__vd__vertices = 320 };
enum : uint32_t { X_GfxWorldDraw__vd__worldVb = 164, L_GfxWorldDraw__vd__worldVb = 328 };
enum : uint32_t { X_GfxWorldDraw__vertexLayerDataSize = 168, L_GfxWorldDraw__vertexLayerDataSize = 336 };
enum : uint32_t { X_GfxWorldDraw__vld__data = 172, L_GfxWorldDraw__vld__data = 344 };
enum : uint32_t { X_GfxWorldDraw__vld__layerVb = 176, L_GfxWorldDraw__vld__layerVb = 352 };
enum : uint32_t { X_GfxWorldDraw__vertexStream2DataSize = 180, L_GfxWorldDraw__vertexStream2DataSize = 360 };
enum : uint32_t { X_GfxWorldDraw__indexCount = 184, L_GfxWorldDraw__indexCount = 364 };
enum : uint32_t { X_GfxWorldDraw__indices = 188, L_GfxWorldDraw__indices = 368 };
static const LayoutSpan SPANS_GfxWorldDraw[] = {{0,0,4},{12,24,4},{156,312,4},{168,336,4},{180,360,8}};

// GfxReflectionProbe
enum : uint32_t { X_sizeof_GfxReflectionProbe = 24, L_sizeof_GfxReflectionProbe = 40 };
enum : uint32_t { X_GfxReflectionProbe__origin = 0, L_GfxReflectionProbe__origin = 0 };
enum : uint32_t { X_GfxReflectionProbe__reflectionImage = 12, L_GfxReflectionProbe__reflectionImage = 16 };
enum : uint32_t { X_GfxReflectionProbe__probeVolumes = 16, L_GfxReflectionProbe__probeVolumes = 24 };
enum : uint32_t { X_GfxReflectionProbe__probeVolumeCount = 20, L_GfxReflectionProbe__probeVolumeCount = 32 };
static const LayoutSpan SPANS_GfxReflectionProbe[] = {{0,0,12},{20,32,4}};

// GfxReflectionProbeVolumeData
enum : uint32_t { X_sizeof_GfxReflectionProbeVolumeData = 96, L_sizeof_GfxReflectionProbeVolumeData = 96 };
enum : uint32_t { X_GfxReflectionProbeVolumeData__volumePlanes = 0, L_GfxReflectionProbeVolumeData__volumePlanes = 0 };
static const LayoutSpan SPANS_GfxReflectionProbeVolumeData[] = {{0,0,96}};

// GfxTexture
enum : uint32_t { X_sizeof_GfxTexture = 4, L_sizeof_GfxTexture = 8 };
enum : uint32_t { X_GfxTexture__basemap = 0, L_GfxTexture__basemap = 0 };
enum : uint32_t { X_GfxTexture__map = 0, L_GfxTexture__map = 0 };
enum : uint32_t { X_GfxTexture__volmap = 0, L_GfxTexture__volmap = 0 };
enum : uint32_t { X_GfxTexture__cubemap = 0, L_GfxTexture__cubemap = 0 };
enum : uint32_t { X_GfxTexture__loadDef = 0, L_GfxTexture__loadDef = 0 };
static const LayoutSpan SPANS_GfxTexture[] = {{0,0,0}};

// GfxLightmapArray
enum : uint32_t { X_sizeof_GfxLightmapArray = 12, L_sizeof_GfxLightmapArray = 24 };
enum : uint32_t { X_GfxLightmapArray__primary = 0, L_GfxLightmapArray__primary = 0 };
enum : uint32_t { X_GfxLightmapArray__secondary = 4, L_GfxLightmapArray__secondary = 8 };
enum : uint32_t { X_GfxLightmapArray__secondaryB = 8, L_GfxLightmapArray__secondaryB = 16 };
static const LayoutSpan SPANS_GfxLightmapArray[] = {{0,0,0}};

// GfxWorldVertexData
enum : uint32_t { X_sizeof_GfxWorldVertexData = 8, L_sizeof_GfxWorldVertexData = 16 };
enum : uint32_t { X_GfxWorldVertexData__vertices = 0, L_GfxWorldVertexData__vertices = 0 };
enum : uint32_t { X_GfxWorldVertexData__worldVb = 4, L_GfxWorldVertexData__worldVb = 8 };
static const LayoutSpan SPANS_GfxWorldVertexData[] = {{0,0,0}};

// GfxWorldVertexLayerData
enum : uint32_t { X_sizeof_GfxWorldVertexLayerData = 8, L_sizeof_GfxWorldVertexLayerData = 16 };
enum : uint32_t { X_GfxWorldVertexLayerData__data = 0, L_GfxWorldVertexLayerData__data = 0 };
enum : uint32_t { X_GfxWorldVertexLayerData__layerVb = 4, L_GfxWorldVertexLayerData__layerVb = 8 };
static const LayoutSpan SPANS_GfxWorldVertexLayerData[] = {{0,0,0}};

// GfxWorldVertex
enum : uint32_t { X_sizeof_GfxWorldVertex = 44, L_sizeof_GfxWorldVertex = 44 };
enum : uint32_t { X_GfxWorldVertex__xyz = 0, L_GfxWorldVertex__xyz = 0 };
enum : uint32_t { X_GfxWorldVertex__binormalSign = 12, L_GfxWorldVertex__binormalSign = 12 };
enum : uint32_t { X_GfxWorldVertex__color = 16, L_GfxWorldVertex__color = 16 };
enum : uint32_t { X_GfxWorldVertex__texCoord = 20, L_GfxWorldVertex__texCoord = 20 };
enum : uint32_t { X_GfxWorldVertex__lmapCoord = 28, L_GfxWorldVertex__lmapCoord = 28 };
enum : uint32_t { X_GfxWorldVertex__normal = 36, L_GfxWorldVertex__normal = 36 };
enum : uint32_t { X_GfxWorldVertex__tangent = 40, L_GfxWorldVertex__tangent = 40 };
static const LayoutSpan SPANS_GfxWorldVertex[] = {{0,0,44}};

// GfxLightGrid
enum : uint32_t { X_sizeof_GfxLightGrid = 56, L_sizeof_GfxLightGrid = 88 };
enum : uint32_t { X_GfxLightGrid__hasLightRegions = 0, L_GfxLightGrid__hasLightRegions = 0 };
enum : uint32_t { X_GfxLightGrid__sunPrimaryLightIndex = 4, L_GfxLightGrid__sunPrimaryLightIndex = 4 };
enum : uint32_t { X_GfxLightGrid__mins = 8, L_GfxLightGrid__mins = 8 };
enum : uint32_t { X_GfxLightGrid__maxs = 14, L_GfxLightGrid__maxs = 14 };
enum : uint32_t { X_GfxLightGrid__rowAxis = 20, L_GfxLightGrid__rowAxis = 20 };
enum : uint32_t { X_GfxLightGrid__colAxis = 24, L_GfxLightGrid__colAxis = 24 };
enum : uint32_t { X_GfxLightGrid__rowDataStart = 28, L_GfxLightGrid__rowDataStart = 32 };
enum : uint32_t { X_GfxLightGrid__rawRowDataSize = 32, L_GfxLightGrid__rawRowDataSize = 40 };
enum : uint32_t { X_GfxLightGrid__rawRowData = 36, L_GfxLightGrid__rawRowData = 48 };
enum : uint32_t { X_GfxLightGrid__entryCount = 40, L_GfxLightGrid__entryCount = 56 };
enum : uint32_t { X_GfxLightGrid__entries = 44, L_GfxLightGrid__entries = 64 };
enum : uint32_t { X_GfxLightGrid__colorCount = 48, L_GfxLightGrid__colorCount = 72 };
enum : uint32_t { X_GfxLightGrid__colors = 52, L_GfxLightGrid__colors = 80 };
static const LayoutSpan SPANS_GfxLightGrid[] = {{0,0,1},{4,4,24},{32,40,4},{40,56,4},{48,72,4}};

// GfxLightGridEntry
enum : uint32_t { X_sizeof_GfxLightGridEntry = 4, L_sizeof_GfxLightGridEntry = 4 };
enum : uint32_t { X_GfxLightGridEntry__colorsIndex = 0, L_GfxLightGridEntry__colorsIndex = 0 };
enum : uint32_t { X_GfxLightGridEntry__primaryLightIndex = 2, L_GfxLightGridEntry__primaryLightIndex = 2 };
enum : uint32_t { X_GfxLightGridEntry__needsTrace = 3, L_GfxLightGridEntry__needsTrace = 3 };
static const LayoutSpan SPANS_GfxLightGridEntry[] = {{0,0,4}};

// GfxCompressedLightGridColors
enum : uint32_t { X_sizeof_GfxCompressedLightGridColors = 168, L_sizeof_GfxCompressedLightGridColors = 168 };
enum : uint32_t { X_GfxCompressedLightGridColors__rgb = 0, L_GfxCompressedLightGridColors__rgb = 0 };
static const LayoutSpan SPANS_GfxCompressedLightGridColors[] = {{0,0,168}};

// GfxBrushModel
enum : uint32_t { X_sizeof_GfxBrushModel = 60, L_sizeof_GfxBrushModel = 60 };
enum : uint32_t { X_GfxBrushModel__writable = 0, L_GfxBrushModel__writable = 0 };
enum : uint32_t { X_GfxBrushModel__bounds = 28, L_GfxBrushModel__bounds = 28 };
enum : uint32_t { X_GfxBrushModel__surfaceCount = 52, L_GfxBrushModel__surfaceCount = 52 };
enum : uint32_t { X_GfxBrushModel__startSurfIndex = 56, L_GfxBrushModel__startSurfIndex = 56 };
static const LayoutSpan SPANS_GfxBrushModel[] = {{0,0,60}};

// MaterialMemory
enum : uint32_t { X_sizeof_MaterialMemory = 8, L_sizeof_MaterialMemory = 16 };
enum : uint32_t { X_MaterialMemory__material = 0, L_MaterialMemory__material = 0 };
enum : uint32_t { X_MaterialMemory__memory = 4, L_MaterialMemory__memory = 8 };
static const LayoutSpan SPANS_MaterialMemory[] = {{4,8,4}};

// sunflare_t
enum : uint32_t { X_sizeof_sunflare_t = 96, L_sizeof_sunflare_t = 112 };
enum : uint32_t { X_sunflare_t__hasValidData = 0, L_sunflare_t__hasValidData = 0 };
enum : uint32_t { X_sunflare_t__spriteMaterial = 4, L_sunflare_t__spriteMaterial = 8 };
enum : uint32_t { X_sunflare_t__flareMaterial = 8, L_sunflare_t__flareMaterial = 16 };
enum : uint32_t { X_sunflare_t__spriteSize = 12, L_sunflare_t__spriteSize = 24 };
enum : uint32_t { X_sunflare_t__flareMinSize = 16, L_sunflare_t__flareMinSize = 28 };
enum : uint32_t { X_sunflare_t__flareMinDot = 20, L_sunflare_t__flareMinDot = 32 };
enum : uint32_t { X_sunflare_t__flareMaxSize = 24, L_sunflare_t__flareMaxSize = 36 };
enum : uint32_t { X_sunflare_t__flareMaxDot = 28, L_sunflare_t__flareMaxDot = 40 };
enum : uint32_t { X_sunflare_t__flareMaxAlpha = 32, L_sunflare_t__flareMaxAlpha = 44 };
enum : uint32_t { X_sunflare_t__flareFadeInTime = 36, L_sunflare_t__flareFadeInTime = 48 };
enum : uint32_t { X_sunflare_t__flareFadeOutTime = 40, L_sunflare_t__flareFadeOutTime = 52 };
enum : uint32_t { X_sunflare_t__blindMinDot = 44, L_sunflare_t__blindMinDot = 56 };
enum : uint32_t { X_sunflare_t__blindMaxDot = 48, L_sunflare_t__blindMaxDot = 60 };
enum : uint32_t { X_sunflare_t__blindMaxDarken = 52, L_sunflare_t__blindMaxDarken = 64 };
enum : uint32_t { X_sunflare_t__blindFadeInTime = 56, L_sunflare_t__blindFadeInTime = 68 };
enum : uint32_t { X_sunflare_t__blindFadeOutTime = 60, L_sunflare_t__blindFadeOutTime = 72 };
enum : uint32_t { X_sunflare_t__glareMinDot = 64, L_sunflare_t__glareMinDot = 76 };
enum : uint32_t { X_sunflare_t__glareMaxDot = 68, L_sunflare_t__glareMaxDot = 80 };
enum : uint32_t { X_sunflare_t__glareMaxLighten = 72, L_sunflare_t__glareMaxLighten = 84 };
enum : uint32_t { X_sunflare_t__glareFadeInTime = 76, L_sunflare_t__glareFadeInTime = 88 };
enum : uint32_t { X_sunflare_t__glareFadeOutTime = 80, L_sunflare_t__glareFadeOutTime = 92 };
enum : uint32_t { X_sunflare_t__sunFxPosition = 84, L_sunflare_t__sunFxPosition = 96 };
static const LayoutSpan SPANS_sunflare_t[] = {{0,0,1},{12,24,84}};

// GfxSceneDynModel
enum : uint32_t { X_sizeof_GfxSceneDynModel = 6, L_sizeof_GfxSceneDynModel = 6 };
enum : uint32_t { X_GfxSceneDynModel__info = 0, L_GfxSceneDynModel__info = 0 };
enum : uint32_t { X_GfxSceneDynModel__dynEntId = 4, L_GfxSceneDynModel__dynEntId = 4 };
static const LayoutSpan SPANS_GfxSceneDynModel[] = {{0,0,6}};

// GfxSceneDynBrush
enum : uint32_t { X_sizeof_GfxSceneDynBrush = 4, L_sizeof_GfxSceneDynBrush = 4 };
enum : uint32_t { X_GfxSceneDynBrush__info = 0, L_GfxSceneDynBrush__info = 0 };
enum : uint32_t { X_GfxSceneDynBrush__dynEntId = 2, L_GfxSceneDynBrush__dynEntId = 2 };
static const LayoutSpan SPANS_GfxSceneDynBrush[] = {{0,0,4}};

// GfxShadowGeometry
enum : uint32_t { X_sizeof_GfxShadowGeometry = 12, L_sizeof_GfxShadowGeometry = 24 };
enum : uint32_t { X_GfxShadowGeometry__surfaceCount = 0, L_GfxShadowGeometry__surfaceCount = 0 };
enum : uint32_t { X_GfxShadowGeometry__smodelCount = 2, L_GfxShadowGeometry__smodelCount = 2 };
enum : uint32_t { X_GfxShadowGeometry__sortedSurfIndex = 4, L_GfxShadowGeometry__sortedSurfIndex = 8 };
enum : uint32_t { X_GfxShadowGeometry__smodelIndex = 8, L_GfxShadowGeometry__smodelIndex = 16 };
static const LayoutSpan SPANS_GfxShadowGeometry[] = {{0,0,4}};

// GfxLightRegion
enum : uint32_t { X_sizeof_GfxLightRegion = 8, L_sizeof_GfxLightRegion = 16 };
enum : uint32_t { X_GfxLightRegion__hullCount = 0, L_GfxLightRegion__hullCount = 0 };
enum : uint32_t { X_GfxLightRegion__hulls = 4, L_GfxLightRegion__hulls = 8 };
static const LayoutSpan SPANS_GfxLightRegion[] = {{0,0,4}};

// GfxLightRegionHull
enum : uint32_t { X_sizeof_GfxLightRegionHull = 80, L_sizeof_GfxLightRegionHull = 88 };
enum : uint32_t { X_GfxLightRegionHull__kdopMidPoint = 0, L_GfxLightRegionHull__kdopMidPoint = 0 };
enum : uint32_t { X_GfxLightRegionHull__kdopHalfSize = 36, L_GfxLightRegionHull__kdopHalfSize = 36 };
enum : uint32_t { X_GfxLightRegionHull__axisCount = 72, L_GfxLightRegionHull__axisCount = 72 };
enum : uint32_t { X_GfxLightRegionHull__axis = 76, L_GfxLightRegionHull__axis = 80 };
static const LayoutSpan SPANS_GfxLightRegionHull[] = {{0,0,76}};

// GfxLightRegionAxis
enum : uint32_t { X_sizeof_GfxLightRegionAxis = 20, L_sizeof_GfxLightRegionAxis = 20 };
enum : uint32_t { X_GfxLightRegionAxis__dir = 0, L_GfxLightRegionAxis__dir = 0 };
enum : uint32_t { X_GfxLightRegionAxis__midPoint = 12, L_GfxLightRegionAxis__midPoint = 12 };
enum : uint32_t { X_GfxLightRegionAxis__halfSize = 16, L_GfxLightRegionAxis__halfSize = 16 };
static const LayoutSpan SPANS_GfxLightRegionAxis[] = {{0,0,20}};

// GfxWorldDpvsStatic
enum : uint32_t { X_sizeof_GfxWorldDpvsStatic = 112, L_sizeof_GfxWorldDpvsStatic = 184 };
enum : uint32_t { X_GfxWorldDpvsStatic__smodelCount = 0, L_GfxWorldDpvsStatic__smodelCount = 0 };
enum : uint32_t { X_GfxWorldDpvsStatic__dynamicSModelCount = 4, L_GfxWorldDpvsStatic__dynamicSModelCount = 4 };
enum : uint32_t { X_GfxWorldDpvsStatic__staticSurfaceCount = 8, L_GfxWorldDpvsStatic__staticSurfaceCount = 8 };
enum : uint32_t { X_GfxWorldDpvsStatic__litSurfsBegin = 12, L_GfxWorldDpvsStatic__litSurfsBegin = 12 };
enum : uint32_t { X_GfxWorldDpvsStatic__litSurfsEnd = 16, L_GfxWorldDpvsStatic__litSurfsEnd = 16 };
enum : uint32_t { X_GfxWorldDpvsStatic__decalSurfsBegin = 20, L_GfxWorldDpvsStatic__decalSurfsBegin = 20 };
enum : uint32_t { X_GfxWorldDpvsStatic__decalSurfsEnd = 24, L_GfxWorldDpvsStatic__decalSurfsEnd = 24 };
enum : uint32_t { X_GfxWorldDpvsStatic__emissiveSurfsBegin = 28, L_GfxWorldDpvsStatic__emissiveSurfsBegin = 28 };
enum : uint32_t { X_GfxWorldDpvsStatic__emissiveSurfsEnd = 32, L_GfxWorldDpvsStatic__emissiveSurfsEnd = 32 };
enum : uint32_t { X_GfxWorldDpvsStatic__smodelVisDataCount = 36, L_GfxWorldDpvsStatic__smodelVisDataCount = 36 };
enum : uint32_t { X_GfxWorldDpvsStatic__surfaceVisDataCount = 40, L_GfxWorldDpvsStatic__surfaceVisDataCount = 40 };
enum : uint32_t { X_GfxWorldDpvsStatic__smodelVisData = 44, L_GfxWorldDpvsStatic__smodelVisData = 48 };
enum : uint32_t { X_GfxWorldDpvsStatic__surfaceVisData = 56, L_GfxWorldDpvsStatic__surfaceVisData = 72 };
enum : uint32_t { X_GfxWorldDpvsStatic__smodelVisDataCameraSaved = 68, L_GfxWorldDpvsStatic__smodelVisDataCameraSaved = 96 };
enum : uint32_t { X_GfxWorldDpvsStatic__surfaceVisDataCameraSaved = 72, L_GfxWorldDpvsStatic__surfaceVisDataCameraSaved = 104 };
enum : uint32_t { X_GfxWorldDpvsStatic__lodData = 76, L_GfxWorldDpvsStatic__lodData = 112 };
enum : uint32_t { X_GfxWorldDpvsStatic__sortedSurfIndex = 80, L_GfxWorldDpvsStatic__sortedSurfIndex = 120 };
enum : uint32_t { X_GfxWorldDpvsStatic__smodelInsts = 84, L_GfxWorldDpvsStatic__smodelInsts = 128 };
enum : uint32_t { X_GfxWorldDpvsStatic__surfaces = 88, L_GfxWorldDpvsStatic__surfaces = 136 };
enum : uint32_t { X_GfxWorldDpvsStatic__cullGroups = 92, L_GfxWorldDpvsStatic__cullGroups = 144 };
enum : uint32_t { X_GfxWorldDpvsStatic__smodelDrawInsts = 96, L_GfxWorldDpvsStatic__smodelDrawInsts = 152 };
enum : uint32_t { X_GfxWorldDpvsStatic__surfaceMaterials = 100, L_GfxWorldDpvsStatic__surfaceMaterials = 160 };
enum : uint32_t { X_GfxWorldDpvsStatic__surfaceCastsSunShadow = 104, L_GfxWorldDpvsStatic__surfaceCastsSunShadow = 168 };
enum : uint32_t { X_GfxWorldDpvsStatic__usageCount = 108, L_GfxWorldDpvsStatic__usageCount = 176 };
static const LayoutSpan SPANS_GfxWorldDpvsStatic[] = {{0,0,44},{108,176,4}};

// GfxStaticModelInst
enum : uint32_t { X_sizeof_GfxStaticModelInst = 40, L_sizeof_GfxStaticModelInst = 40 };
enum : uint32_t { X_GfxStaticModelInst__mins = 0, L_GfxStaticModelInst__mins = 0 };
enum : uint32_t { X_GfxStaticModelInst__maxs = 12, L_GfxStaticModelInst__maxs = 12 };
enum : uint32_t { X_GfxStaticModelInst__lightingOrigin = 24, L_GfxStaticModelInst__lightingOrigin = 24 };
enum : uint32_t { X_GfxStaticModelInst__groundLighting = 36, L_GfxStaticModelInst__groundLighting = 36 };
static const LayoutSpan SPANS_GfxStaticModelInst[] = {{0,0,40}};

// GfxSurface
enum : uint32_t { X_sizeof_GfxSurface = 80, L_sizeof_GfxSurface = 88 };
enum : uint32_t { X_GfxSurface__tris = 0, L_GfxSurface__tris = 0 };
enum : uint32_t { X_GfxSurface__material = 48, L_GfxSurface__material = 48 };
enum : uint32_t { X_GfxSurface__lightmapIndex = 52, L_GfxSurface__lightmapIndex = 56 };
enum : uint32_t { X_GfxSurface__reflectionProbeIndex = 53, L_GfxSurface__reflectionProbeIndex = 57 };
enum : uint32_t { X_GfxSurface__primaryLightIndex = 54, L_GfxSurface__primaryLightIndex = 58 };
enum : uint32_t { X_GfxSurface__flags = 55, L_GfxSurface__flags = 59 };
enum : uint32_t { X_GfxSurface__bounds = 56, L_GfxSurface__bounds = 60 };
static const LayoutSpan SPANS_GfxSurface[] = {{0,0,48},{52,56,28}};

// GfxCullGroup
enum : uint32_t { X_sizeof_GfxCullGroup = 32, L_sizeof_GfxCullGroup = 32 };
enum : uint32_t { X_GfxCullGroup__mins = 0, L_GfxCullGroup__mins = 0 };
enum : uint32_t { X_GfxCullGroup__maxs = 12, L_GfxCullGroup__maxs = 12 };
enum : uint32_t { X_GfxCullGroup__surfaceCount = 24, L_GfxCullGroup__surfaceCount = 24 };
enum : uint32_t { X_GfxCullGroup__startSurfIndex = 28, L_GfxCullGroup__startSurfIndex = 28 };
static const LayoutSpan SPANS_GfxCullGroup[] = {{0,0,32}};

// GfxStaticModelDrawInst
enum : uint32_t { X_sizeof_GfxStaticModelDrawInst = 76, L_sizeof_GfxStaticModelDrawInst = 80 };
enum : uint32_t { X_GfxStaticModelDrawInst__cullDist = 0, L_GfxStaticModelDrawInst__cullDist = 0 };
enum : uint32_t { X_GfxStaticModelDrawInst__placement = 4, L_GfxStaticModelDrawInst__placement = 4 };
enum : uint32_t { X_GfxStaticModelDrawInst__model = 56, L_GfxStaticModelDrawInst__model = 56 };
enum : uint32_t { X_GfxStaticModelDrawInst__flags = 60, L_GfxStaticModelDrawInst__flags = 64 };
enum : uint32_t { X_GfxStaticModelDrawInst__smodelCacheIndex = 64, L_GfxStaticModelDrawInst__smodelCacheIndex = 68 };
enum : uint32_t { X_GfxStaticModelDrawInst__lightingHandle = 72, L_GfxStaticModelDrawInst__lightingHandle = 76 };
enum : uint32_t { X_GfxStaticModelDrawInst__reflectionProbeIndex = 74, L_GfxStaticModelDrawInst__reflectionProbeIndex = 78 };
enum : uint32_t { X_GfxStaticModelDrawInst__primaryLightIndex = 75, L_GfxStaticModelDrawInst__primaryLightIndex = 79 };
static const LayoutSpan SPANS_GfxStaticModelDrawInst[] = {{0,0,56},{60,64,16}};

// GfxDrawSurf
enum : uint32_t { X_sizeof_GfxDrawSurf = 8, L_sizeof_GfxDrawSurf = 8 };
enum : uint32_t { X_GfxDrawSurf__fields = 0, L_GfxDrawSurf__fields = 0 };
enum : uint32_t { X_GfxDrawSurf__packed = 0, L_GfxDrawSurf__packed = 0 };
static const LayoutSpan SPANS_GfxDrawSurf[] = {{0,0,8},{0,0,8}};

// GfxWorldDpvsDynamic
enum : uint32_t { X_sizeof_GfxWorldDpvsDynamic = 48, L_sizeof_GfxWorldDpvsDynamic = 80 };
enum : uint32_t { X_GfxWorldDpvsDynamic__dynEntClientWordCount = 0, L_GfxWorldDpvsDynamic__dynEntClientWordCount = 0 };
enum : uint32_t { X_GfxWorldDpvsDynamic__dynEntClientCount = 8, L_GfxWorldDpvsDynamic__dynEntClientCount = 8 };
enum : uint32_t { X_GfxWorldDpvsDynamic__dynEntCellBits = 16, L_GfxWorldDpvsDynamic__dynEntCellBits = 16 };
enum : uint32_t { X_GfxWorldDpvsDynamic__dynEntVisData = 24, L_GfxWorldDpvsDynamic__dynEntVisData = 32 };
static const LayoutSpan SPANS_GfxWorldDpvsDynamic[] = {{0,0,16}};

// GfxWorldLodChain
enum : uint32_t { X_sizeof_GfxWorldLodChain = 24, L_sizeof_GfxWorldLodChain = 24 };
enum : uint32_t { X_GfxWorldLodChain__origin = 0, L_GfxWorldLodChain__origin = 0 };
enum : uint32_t { X_GfxWorldLodChain__lastDist = 12, L_GfxWorldLodChain__lastDist = 12 };
enum : uint32_t { X_GfxWorldLodChain__firstLodInfo = 16, L_GfxWorldLodChain__firstLodInfo = 16 };
enum : uint32_t { X_GfxWorldLodChain__lodInfoCount = 20, L_GfxWorldLodChain__lodInfoCount = 20 };
static const LayoutSpan SPANS_GfxWorldLodChain[] = {{0,0,22}};

// GfxWorldLodInfo
enum : uint32_t { X_sizeof_GfxWorldLodInfo = 12, L_sizeof_GfxWorldLodInfo = 12 };
enum : uint32_t { X_GfxWorldLodInfo__dist = 0, L_GfxWorldLodInfo__dist = 0 };
enum : uint32_t { X_GfxWorldLodInfo__firstSurf = 4, L_GfxWorldLodInfo__firstSurf = 4 };
enum : uint32_t { X_GfxWorldLodInfo__surfCount = 8, L_GfxWorldLodInfo__surfCount = 8 };
static const LayoutSpan SPANS_GfxWorldLodInfo[] = {{0,0,10}};

// GfxWaterBuffer
enum : uint32_t { X_sizeof_GfxWaterBuffer = 8, L_sizeof_GfxWaterBuffer = 16 };
enum : uint32_t { X_GfxWaterBuffer__bufferSize = 0, L_GfxWaterBuffer__bufferSize = 0 };
enum : uint32_t { X_GfxWaterBuffer__buffer = 4, L_GfxWaterBuffer__buffer = 8 };
static const LayoutSpan SPANS_GfxWaterBuffer[] = {{0,0,4}};

// Occluder
enum : uint32_t { X_sizeof_Occluder = 68, L_sizeof_Occluder = 68 };
enum : uint32_t { X_Occluder__flags = 0, L_Occluder__flags = 0 };
enum : uint32_t { X_Occluder__name = 4, L_Occluder__name = 4 };
enum : uint32_t { X_Occluder__points = 20, L_Occluder__points = 20 };
static const LayoutSpan SPANS_Occluder[] = {{0,0,68}};

// GfxOutdoorBounds
enum : uint32_t { X_sizeof_GfxOutdoorBounds = 24, L_sizeof_GfxOutdoorBounds = 24 };
enum : uint32_t { X_GfxOutdoorBounds__bounds = 0, L_GfxOutdoorBounds__bounds = 0 };
static const LayoutSpan SPANS_GfxOutdoorBounds[] = {{0,0,24}};

// GfxHeroLight
enum : uint32_t { X_sizeof_GfxHeroLight = 56, L_sizeof_GfxHeroLight = 56 };
enum : uint32_t { X_GfxHeroLight__type = 0, L_GfxHeroLight__type = 0 };
enum : uint32_t { X_GfxHeroLight__unused = 1, L_GfxHeroLight__unused = 1 };
enum : uint32_t { X_GfxHeroLight__color = 4, L_GfxHeroLight__color = 4 };
enum : uint32_t { X_GfxHeroLight__dir = 16, L_GfxHeroLight__dir = 16 };
enum : uint32_t { X_GfxHeroLight__origin = 28, L_GfxHeroLight__origin = 28 };
enum : uint32_t { X_GfxHeroLight__radius = 40, L_GfxHeroLight__radius = 40 };
enum : uint32_t { X_GfxHeroLight__cosHalfFovOuter = 44, L_GfxHeroLight__cosHalfFovOuter = 44 };
enum : uint32_t { X_GfxHeroLight__cosHalfFovInner = 48, L_GfxHeroLight__cosHalfFovInner = 48 };
enum : uint32_t { X_GfxHeroLight__exponent = 52, L_GfxHeroLight__exponent = 52 };
static const LayoutSpan SPANS_GfxHeroLight[] = {{0,0,56}};

// GfxHeroLightTree
enum : uint32_t { X_sizeof_GfxHeroLightTree = 24, L_sizeof_GfxHeroLightTree = 24 };
enum : uint32_t { X_GfxHeroLightTree__mins = 0, L_GfxHeroLightTree__mins = 0 };
enum : uint32_t { X_GfxHeroLightTree__maxs = 12, L_GfxHeroLightTree__maxs = 12 };
static const LayoutSpan SPANS_GfxHeroLightTree[] = {{0,0,24}};

// GameWorldMp
enum : uint32_t { X_sizeof_GameWorldMp = 44, L_sizeof_GameWorldMp = 88 };
enum : uint32_t { X_GameWorldMp__name = 0, L_GameWorldMp__name = 0 };
enum : uint32_t { X_GameWorldMp__path__nodeCount = 4, L_GameWorldMp__path__nodeCount = 8 };
enum : uint32_t { X_GameWorldMp__path__nodes = 8, L_GameWorldMp__path__nodes = 16 };
enum : uint32_t { X_GameWorldMp__path__basenodes = 12, L_GameWorldMp__path__basenodes = 24 };
enum : uint32_t { X_GameWorldMp__path__chainNodeCount = 16, L_GameWorldMp__path__chainNodeCount = 32 };
enum : uint32_t { X_GameWorldMp__path__chainNodeForNode = 20, L_GameWorldMp__path__chainNodeForNode = 40 };
enum : uint32_t { X_GameWorldMp__path__nodeForChainNode = 24, L_GameWorldMp__path__nodeForChainNode = 48 };
enum : uint32_t { X_GameWorldMp__path__visBytes = 28, L_GameWorldMp__path__visBytes = 56 };
enum : uint32_t { X_GameWorldMp__path__pathVis = 32, L_GameWorldMp__path__pathVis = 64 };
enum : uint32_t { X_GameWorldMp__path__nodeTreeCount = 36, L_GameWorldMp__path__nodeTreeCount = 72 };
enum : uint32_t { X_GameWorldMp__path__nodeTree = 40, L_GameWorldMp__path__nodeTree = 80 };
static const LayoutSpan SPANS_GameWorldMp[] = {{4,8,4},{16,32,4},{28,56,4},{36,72,4}};

// PathData
enum : uint32_t { X_sizeof_PathData = 40, L_sizeof_PathData = 80 };
enum : uint32_t { X_PathData__nodeCount = 0, L_PathData__nodeCount = 0 };
enum : uint32_t { X_PathData__nodes = 4, L_PathData__nodes = 8 };
enum : uint32_t { X_PathData__basenodes = 8, L_PathData__basenodes = 16 };
enum : uint32_t { X_PathData__chainNodeCount = 12, L_PathData__chainNodeCount = 24 };
enum : uint32_t { X_PathData__chainNodeForNode = 16, L_PathData__chainNodeForNode = 32 };
enum : uint32_t { X_PathData__nodeForChainNode = 20, L_PathData__nodeForChainNode = 40 };
enum : uint32_t { X_PathData__visBytes = 24, L_PathData__visBytes = 48 };
enum : uint32_t { X_PathData__pathVis = 28, L_PathData__pathVis = 56 };
enum : uint32_t { X_PathData__nodeTreeCount = 32, L_PathData__nodeTreeCount = 64 };
enum : uint32_t { X_PathData__nodeTree = 36, L_PathData__nodeTree = 72 };
static const LayoutSpan SPANS_PathData[] = {{0,0,4},{12,24,4},{24,48,4},{32,64,4}};

// pathnode_t
enum : uint32_t { X_sizeof_pathnode_t = 128, L_sizeof_pathnode_t = 152 };
enum : uint32_t { X_pathnode_t__constant__type = 0, L_pathnode_t__constant__type = 0 };
enum : uint32_t { X_pathnode_t__constant__spawnflags = 4, L_pathnode_t__constant__spawnflags = 4 };
enum : uint32_t { X_pathnode_t__constant__targetname = 6, L_pathnode_t__constant__targetname = 6 };
enum : uint32_t { X_pathnode_t__constant__script_linkName = 8, L_pathnode_t__constant__script_linkName = 8 };
enum : uint32_t { X_pathnode_t__constant__script_noteworthy = 10, L_pathnode_t__constant__script_noteworthy = 10 };
enum : uint32_t { X_pathnode_t__constant__target = 12, L_pathnode_t__constant__target = 12 };
enum : uint32_t { X_pathnode_t__constant__animscript = 14, L_pathnode_t__constant__animscript = 14 };
enum : uint32_t { X_pathnode_t__constant__animscriptfunc = 16, L_pathnode_t__constant__animscriptfunc = 16 };
enum : uint32_t { X_pathnode_t__constant__vOrigin = 20, L_pathnode_t__constant__vOrigin = 20 };
enum : uint32_t { X_pathnode_t__constant__fAngle = 32, L_pathnode_t__constant__fAngle = 32 };
enum : uint32_t { X_pathnode_t__constant__forward = 36, L_pathnode_t__constant__forward = 36 };
enum : uint32_t { X_pathnode_t__constant__fRadius = 44, L_pathnode_t__constant__fRadius = 44 };
enum : uint32_t { X_pathnode_t__constant__minUseDistSq = 48, L_pathnode_t__constant__minUseDistSq = 48 };
enum : uint32_t { X_pathnode_t__constant__wOverlapNode = 52, L_pathnode_t__constant__wOverlapNode = 52 };
enum : uint32_t { X_pathnode_t__constant__wChainId = 56, L_pathnode_t__constant__wChainId = 56 };
enum : uint32_t { X_pathnode_t__constant__wChainDepth = 58, L_pathnode_t__constant__wChainDepth = 58 };
enum : uint32_t { X_pathnode_t__constant__wChainParent = 60, L_pathnode_t__constant__wChainParent = 60 };
enum : uint32_t { X_pathnode_t__constant__totalLinkCount = 62, L_pathnode_t__constant__totalLinkCount = 62 };
enum : uint32_t { X_pathnode_t__constant__Links = 64, L_pathnode_t__constant__Links = 64 };
enum : uint32_t { X_pathnode_t__dynamic__pOwner = 68, L_pathnode_t__dynamic__pOwner = 72 };
enum : uint32_t { X_pathnode_t__dynamic__iFreeTime = 72, L_pathnode_t__dynamic__iFreeTime = 76 };
enum : uint32_t { X_pathnode_t__dynamic__iValidTime = 76, L_pathnode_t__dynamic__iValidTime = 80 };
enum : uint32_t { X_pathnode_t__dynamic__inPlayerLOSTime = 88, L_pathnode_t__dynamic__inPlayerLOSTime = 92 };
enum : uint32_t { X_pathnode_t__dynamic__wLinkCount = 92, L_pathnode_t__dynamic__wLinkCount = 96 };
enum : uint32_t { X_pathnode_t__dynamic__wOverlapCount = 94, L_pathnode_t__dynamic__wOverlapCount = 98 };
enum : uint32_t { X_pathnode_t__dynamic__turretEntNumber = 96, L_pathnode_t__dynamic__turretEntNumber = 100 };
enum : uint32_t { X_pathnode_t__dynamic__userCount = 98, L_pathnode_t__dynamic__userCount = 102 };
enum : uint32_t { X_pathnode_t__transient__iSearchFrame = 100, L_pathnode_t__transient__iSearchFrame = 104 };
enum : uint32_t { X_pathnode_t__transient__pNextOpen = 104, L_pathnode_t__transient__pNextOpen = 112 };
enum : uint32_t { X_pathnode_t__transient__pPrevOpen = 108, L_pathnode_t__transient__pPrevOpen = 120 };
enum : uint32_t { X_pathnode_t__transient__pParent = 112, L_pathnode_t__transient__pParent = 128 };
enum : uint32_t { X_pathnode_t__transient__fCost = 116, L_pathnode_t__transient__fCost = 136 };
enum : uint32_t { X_pathnode_t__transient__fHeuristic = 120, L_pathnode_t__transient__fHeuristic = 140 };
enum : uint32_t { X_pathnode_t__transient__costFactor = 124, L_pathnode_t__transient__costFactor = 144 };
static const LayoutSpan SPANS_pathnode_t[] = {{0,0,64},{68,72,36},{116,136,12}};

// pathnode_constant_t
enum : uint32_t { X_sizeof_pathnode_constant_t = 68, L_sizeof_pathnode_constant_t = 72 };
enum : uint32_t { X_pathnode_constant_t__type = 0, L_pathnode_constant_t__type = 0 };
enum : uint32_t { X_pathnode_constant_t__spawnflags = 4, L_pathnode_constant_t__spawnflags = 4 };
enum : uint32_t { X_pathnode_constant_t__targetname = 6, L_pathnode_constant_t__targetname = 6 };
enum : uint32_t { X_pathnode_constant_t__script_linkName = 8, L_pathnode_constant_t__script_linkName = 8 };
enum : uint32_t { X_pathnode_constant_t__script_noteworthy = 10, L_pathnode_constant_t__script_noteworthy = 10 };
enum : uint32_t { X_pathnode_constant_t__target = 12, L_pathnode_constant_t__target = 12 };
enum : uint32_t { X_pathnode_constant_t__animscript = 14, L_pathnode_constant_t__animscript = 14 };
enum : uint32_t { X_pathnode_constant_t__animscriptfunc = 16, L_pathnode_constant_t__animscriptfunc = 16 };
enum : uint32_t { X_pathnode_constant_t__vOrigin = 20, L_pathnode_constant_t__vOrigin = 20 };
enum : uint32_t { X_pathnode_constant_t__fAngle = 32, L_pathnode_constant_t__fAngle = 32 };
enum : uint32_t { X_pathnode_constant_t__forward = 36, L_pathnode_constant_t__forward = 36 };
enum : uint32_t { X_pathnode_constant_t__fRadius = 44, L_pathnode_constant_t__fRadius = 44 };
enum : uint32_t { X_pathnode_constant_t__minUseDistSq = 48, L_pathnode_constant_t__minUseDistSq = 48 };
enum : uint32_t { X_pathnode_constant_t__wOverlapNode = 52, L_pathnode_constant_t__wOverlapNode = 52 };
enum : uint32_t { X_pathnode_constant_t__wChainId = 56, L_pathnode_constant_t__wChainId = 56 };
enum : uint32_t { X_pathnode_constant_t__wChainDepth = 58, L_pathnode_constant_t__wChainDepth = 58 };
enum : uint32_t { X_pathnode_constant_t__wChainParent = 60, L_pathnode_constant_t__wChainParent = 60 };
enum : uint32_t { X_pathnode_constant_t__totalLinkCount = 62, L_pathnode_constant_t__totalLinkCount = 62 };
enum : uint32_t { X_pathnode_constant_t__Links = 64, L_pathnode_constant_t__Links = 64 };
static const LayoutSpan SPANS_pathnode_constant_t[] = {{0,0,64}};

// pathnode_dynamic_t
enum : uint32_t { X_sizeof_pathnode_dynamic_t = 32, L_sizeof_pathnode_dynamic_t = 32 };
enum : uint32_t { X_pathnode_dynamic_t__pOwner = 0, L_pathnode_dynamic_t__pOwner = 0 };
enum : uint32_t { X_pathnode_dynamic_t__iFreeTime = 4, L_pathnode_dynamic_t__iFreeTime = 4 };
enum : uint32_t { X_pathnode_dynamic_t__iValidTime = 8, L_pathnode_dynamic_t__iValidTime = 8 };
enum : uint32_t { X_pathnode_dynamic_t__inPlayerLOSTime = 20, L_pathnode_dynamic_t__inPlayerLOSTime = 20 };
enum : uint32_t { X_pathnode_dynamic_t__wLinkCount = 24, L_pathnode_dynamic_t__wLinkCount = 24 };
enum : uint32_t { X_pathnode_dynamic_t__wOverlapCount = 26, L_pathnode_dynamic_t__wOverlapCount = 26 };
enum : uint32_t { X_pathnode_dynamic_t__turretEntNumber = 28, L_pathnode_dynamic_t__turretEntNumber = 28 };
enum : uint32_t { X_pathnode_dynamic_t__userCount = 30, L_pathnode_dynamic_t__userCount = 30 };
static const LayoutSpan SPANS_pathnode_dynamic_t[] = {{0,0,32}};

// pathnode_transient_t
enum : uint32_t { X_sizeof_pathnode_transient_t = 28, L_sizeof_pathnode_transient_t = 48 };
enum : uint32_t { X_pathnode_transient_t__iSearchFrame = 0, L_pathnode_transient_t__iSearchFrame = 0 };
enum : uint32_t { X_pathnode_transient_t__pNextOpen = 4, L_pathnode_transient_t__pNextOpen = 8 };
enum : uint32_t { X_pathnode_transient_t__pPrevOpen = 8, L_pathnode_transient_t__pPrevOpen = 16 };
enum : uint32_t { X_pathnode_transient_t__pParent = 12, L_pathnode_transient_t__pParent = 24 };
enum : uint32_t { X_pathnode_transient_t__fCost = 16, L_pathnode_transient_t__fCost = 32 };
enum : uint32_t { X_pathnode_transient_t__fHeuristic = 20, L_pathnode_transient_t__fHeuristic = 36 };
enum : uint32_t { X_pathnode_transient_t__costFactor = 24, L_pathnode_transient_t__costFactor = 40 };
static const LayoutSpan SPANS_pathnode_transient_t[] = {{0,0,4},{16,32,12}};

// pathlink_s
enum : uint32_t { X_sizeof_pathlink_s = 12, L_sizeof_pathlink_s = 12 };
enum : uint32_t { X_pathlink_s__fDist = 0, L_pathlink_s__fDist = 0 };
enum : uint32_t { X_pathlink_s__nodeNum = 4, L_pathlink_s__nodeNum = 4 };
enum : uint32_t { X_pathlink_s__disconnectCount = 6, L_pathlink_s__disconnectCount = 6 };
enum : uint32_t { X_pathlink_s__negotiationLink = 7, L_pathlink_s__negotiationLink = 7 };
enum : uint32_t { X_pathlink_s__ubBadPlaceCount = 8, L_pathlink_s__ubBadPlaceCount = 8 };
static const LayoutSpan SPANS_pathlink_s[] = {{0,0,12}};

// pathbasenode_t
enum : uint32_t { X_sizeof_pathbasenode_t = 16, L_sizeof_pathbasenode_t = 16 };
enum : uint32_t { X_pathbasenode_t__vOrigin = 0, L_pathbasenode_t__vOrigin = 0 };
enum : uint32_t { X_pathbasenode_t__type = 12, L_pathbasenode_t__type = 12 };
static const LayoutSpan SPANS_pathbasenode_t[] = {{0,0,16}};

// pathnode_tree_t
enum : uint32_t { X_sizeof_pathnode_tree_t = 16, L_sizeof_pathnode_tree_t = 24 };
enum : uint32_t { X_pathnode_tree_t__axis = 0, L_pathnode_tree_t__axis = 0 };
enum : uint32_t { X_pathnode_tree_t__dist = 4, L_pathnode_tree_t__dist = 4 };
enum : uint32_t { X_pathnode_tree_t__u = 8, L_pathnode_tree_t__u = 8, XN_pathnode_tree_t__u = 8, LN_pathnode_tree_t__u = 16 };
static const LayoutSpan SPANS_pathnode_tree_t[] = {{0,0,8}};

// pathnode_tree_nodes_t
enum : uint32_t { X_sizeof_pathnode_tree_nodes_t = 8, L_sizeof_pathnode_tree_nodes_t = 16 };
enum : uint32_t { X_pathnode_tree_nodes_t__nodeCount = 0, L_pathnode_tree_nodes_t__nodeCount = 0 };
enum : uint32_t { X_pathnode_tree_nodes_t__nodes = 4, L_pathnode_tree_nodes_t__nodes = 8 };
static const LayoutSpan SPANS_pathnode_tree_nodes_t[] = {{0,0,4}};

// clipMap_t
enum : uint32_t { X_sizeof_clipMap_t = 332, L_sizeof_clipMap_t = 568 };
enum : uint32_t { X_clipMap_t__name = 0, L_clipMap_t__name = 0 };
enum : uint32_t { X_clipMap_t__isInUse = 4, L_clipMap_t__isInUse = 8 };
enum : uint32_t { X_clipMap_t__planeCount = 8, L_clipMap_t__planeCount = 12 };
enum : uint32_t { X_clipMap_t__planes = 12, L_clipMap_t__planes = 16 };
enum : uint32_t { X_clipMap_t__numStaticModels = 16, L_clipMap_t__numStaticModels = 24 };
enum : uint32_t { X_clipMap_t__staticModelList = 20, L_clipMap_t__staticModelList = 32 };
enum : uint32_t { X_clipMap_t__numMaterials = 24, L_clipMap_t__numMaterials = 40 };
enum : uint32_t { X_clipMap_t__materials = 28, L_clipMap_t__materials = 48 };
enum : uint32_t { X_clipMap_t__numBrushSides = 32, L_clipMap_t__numBrushSides = 56 };
enum : uint32_t { X_clipMap_t__brushsides = 36, L_clipMap_t__brushsides = 64 };
enum : uint32_t { X_clipMap_t__numNodes = 40, L_clipMap_t__numNodes = 72 };
enum : uint32_t { X_clipMap_t__nodes = 44, L_clipMap_t__nodes = 80 };
enum : uint32_t { X_clipMap_t__numLeafs = 48, L_clipMap_t__numLeafs = 88 };
enum : uint32_t { X_clipMap_t__leafs = 52, L_clipMap_t__leafs = 96 };
enum : uint32_t { X_clipMap_t__leafbrushNodesCount = 56, L_clipMap_t__leafbrushNodesCount = 104 };
enum : uint32_t { X_clipMap_t__leafbrushNodes = 60, L_clipMap_t__leafbrushNodes = 112 };
enum : uint32_t { X_clipMap_t__numLeafBrushes = 64, L_clipMap_t__numLeafBrushes = 120 };
enum : uint32_t { X_clipMap_t__leafbrushes = 68, L_clipMap_t__leafbrushes = 128 };
enum : uint32_t { X_clipMap_t__numLeafSurfaces = 72, L_clipMap_t__numLeafSurfaces = 136 };
enum : uint32_t { X_clipMap_t__leafsurfaces = 76, L_clipMap_t__leafsurfaces = 144 };
enum : uint32_t { X_clipMap_t__vertCount = 80, L_clipMap_t__vertCount = 152 };
enum : uint32_t { X_clipMap_t__verts = 84, L_clipMap_t__verts = 160 };
enum : uint32_t { X_clipMap_t__numBrushVerts = 88, L_clipMap_t__numBrushVerts = 168 };
enum : uint32_t { X_clipMap_t__brushVerts = 92, L_clipMap_t__brushVerts = 176 };
enum : uint32_t { X_clipMap_t__nuinds = 96, L_clipMap_t__nuinds = 184 };
enum : uint32_t { X_clipMap_t__uinds = 100, L_clipMap_t__uinds = 192 };
enum : uint32_t { X_clipMap_t__triCount = 104, L_clipMap_t__triCount = 200 };
enum : uint32_t { X_clipMap_t__triIndices = 108, L_clipMap_t__triIndices = 208 };
enum : uint32_t { X_clipMap_t__triEdgeIsWalkable = 112, L_clipMap_t__triEdgeIsWalkable = 216 };
enum : uint32_t { X_clipMap_t__borderCount = 116, L_clipMap_t__borderCount = 224 };
enum : uint32_t { X_clipMap_t__borders = 120, L_clipMap_t__borders = 232 };
enum : uint32_t { X_clipMap_t__partitionCount = 124, L_clipMap_t__partitionCount = 240 };
enum : uint32_t { X_clipMap_t__partitions = 128, L_clipMap_t__partitions = 248 };
enum : uint32_t { X_clipMap_t__aabbTreeCount = 132, L_clipMap_t__aabbTreeCount = 256 };
enum : uint32_t { X_clipMap_t__aabbTrees = 136, L_clipMap_t__aabbTrees = 264 };
enum : uint32_t { X_clipMap_t__numSubModels = 140, L_clipMap_t__numSubModels = 272 };
enum : uint32_t { X_clipMap_t__cmodels = 144, L_clipMap_t__cmodels = 280 };
enum : uint32_t { X_clipMap_t__numBrushes = 148, L_clipMap_t__numBrushes = 288 };
enum : uint32_t { X_clipMap_t__brushes = 152, L_clipMap_t__brushes = 296 };
enum : uint32_t { X_clipMap_t__numClusters = 156, L_clipMap_t__numClusters = 304 };
enum : uint32_t { X_clipMap_t__clusterBytes = 160, L_clipMap_t__clusterBytes = 308 };
enum : uint32_t { X_clipMap_t__visibility = 164, L_clipMap_t__visibility = 312 };
enum : uint32_t { X_clipMap_t__vised = 168, L_clipMap_t__vised = 320 };
enum : uint32_t { X_clipMap_t__mapEnts = 172, L_clipMap_t__mapEnts = 328 };
enum : uint32_t { X_clipMap_t__box_brush = 176, L_clipMap_t__box_brush = 336 };
enum : uint32_t { X_clipMap_t__box_model__mins = 180, L_clipMap_t__box_model__mins = 344 };
enum : uint32_t { X_clipMap_t__box_model__maxs = 192, L_clipMap_t__box_model__maxs = 356 };
enum : uint32_t { X_clipMap_t__box_model__radius = 204, L_clipMap_t__box_model__radius = 368 };
enum : uint32_t { X_clipMap_t__box_model__leaf__firstCollAabbIndex = 208, L_clipMap_t__box_model__leaf__firstCollAabbIndex = 372 };
enum : uint32_t { X_clipMap_t__box_model__leaf__collAabbCount = 210, L_clipMap_t__box_model__leaf__collAabbCount = 374 };
enum : uint32_t { X_clipMap_t__box_model__leaf__brushContents = 212, L_clipMap_t__box_model__leaf__brushContents = 376 };
enum : uint32_t { X_clipMap_t__box_model__leaf__terrainContents = 216, L_clipMap_t__box_model__leaf__terrainContents = 380 };
enum : uint32_t { X_clipMap_t__box_model__leaf__mins = 220, L_clipMap_t__box_model__leaf__mins = 384 };
enum : uint32_t { X_clipMap_t__box_model__leaf__maxs = 232, L_clipMap_t__box_model__leaf__maxs = 396 };
enum : uint32_t { X_clipMap_t__box_model__leaf__leafBrushNode = 244, L_clipMap_t__box_model__leaf__leafBrushNode = 408 };
enum : uint32_t { X_clipMap_t__box_model__leaf__cluster = 248, L_clipMap_t__box_model__leaf__cluster = 412 };
enum : uint32_t { X_clipMap_t__originalDynEntCount = 252, L_clipMap_t__originalDynEntCount = 416 };
enum : uint32_t { X_clipMap_t__dynEntCount = 254, L_clipMap_t__dynEntCount = 418 };
enum : uint32_t { X_clipMap_t__dynEntDefList = 264, L_clipMap_t__dynEntDefList = 432 };
enum : uint32_t { X_clipMap_t__dynEntPoseList = 272, L_clipMap_t__dynEntPoseList = 448 };
enum : uint32_t { X_clipMap_t__dynEntClientList = 280, L_clipMap_t__dynEntClientList = 464 };
enum : uint32_t { X_clipMap_t__dynEntServerList = 288, L_clipMap_t__dynEntServerList = 480 };
enum : uint32_t { X_clipMap_t__dynEntCollList = 296, L_clipMap_t__dynEntCollList = 496 };
enum : uint32_t { X_clipMap_t__num_constraints = 312, L_clipMap_t__num_constraints = 528 };
enum : uint32_t { X_clipMap_t__constraints = 316, L_clipMap_t__constraints = 536 };
enum : uint32_t { X_clipMap_t__max_ropes = 320, L_clipMap_t__max_ropes = 544 };
enum : uint32_t { X_clipMap_t__ropes = 324, L_clipMap_t__ropes = 552 };
enum : uint32_t { X_clipMap_t__checksum = 328, L_clipMap_t__checksum = 560 };
static const LayoutSpan SPANS_clipMap_t[] = {{4,8,8},{16,24,4},{24,40,4},{32,56,4},{40,72,4},{48,88,4},{56,104,4},{64,120,4},{72,136,4},{80,152,4},{88,168,4},{96,184,4},{104,200,4},{116,224,4},{124,240,4},{132,256,4},{140,272,4},{148,288,2},{156,304,8},{168,320,4},{180,344,70},{252,416,10},{312,528,4},{320,544,4},{328,560,4}};

// cStaticModel_s
enum : uint32_t { X_sizeof_cStaticModel_s = 80, L_sizeof_cStaticModel_s = 88 };
enum : uint32_t { X_cStaticModel_s__writable = 0, L_cStaticModel_s__writable = 0 };
enum : uint32_t { X_cStaticModel_s__xmodel = 4, L_cStaticModel_s__xmodel = 8 };
enum : uint32_t { X_cStaticModel_s__origin = 8, L_cStaticModel_s__origin = 16 };
enum : uint32_t { X_cStaticModel_s__invScaledAxis = 20, L_cStaticModel_s__invScaledAxis = 28 };
enum : uint32_t { X_cStaticModel_s__absmin = 56, L_cStaticModel_s__absmin = 64 };
enum : uint32_t { X_cStaticModel_s__absmax = 68, L_cStaticModel_s__absmax = 76 };
static const LayoutSpan SPANS_cStaticModel_s[] = {{0,0,2},{8,16,72}};

// dmaterial_t
enum : uint32_t { X_sizeof_dmaterial_t = 72, L_sizeof_dmaterial_t = 72 };
enum : uint32_t { X_dmaterial_t__material = 0, L_dmaterial_t__material = 0 };
enum : uint32_t { X_dmaterial_t__surfaceFlags = 64, L_dmaterial_t__surfaceFlags = 64 };
enum : uint32_t { X_dmaterial_t__contentFlags = 68, L_dmaterial_t__contentFlags = 68 };
static const LayoutSpan SPANS_dmaterial_t[] = {{0,0,72}};

// cbrushside_t
enum : uint32_t { X_sizeof_cbrushside_t = 12, L_sizeof_cbrushside_t = 16 };
enum : uint32_t { X_cbrushside_t__plane = 0, L_cbrushside_t__plane = 0 };
enum : uint32_t { X_cbrushside_t__cflags = 4, L_cbrushside_t__cflags = 8 };
enum : uint32_t { X_cbrushside_t__sflags = 8, L_cbrushside_t__sflags = 12 };
static const LayoutSpan SPANS_cbrushside_t[] = {{4,8,8}};

// cNode_t
enum : uint32_t { X_sizeof_cNode_t = 8, L_sizeof_cNode_t = 16 };
enum : uint32_t { X_cNode_t__plane = 0, L_cNode_t__plane = 0 };
enum : uint32_t { X_cNode_t__children = 4, L_cNode_t__children = 8 };
static const LayoutSpan SPANS_cNode_t[] = {{4,8,4}};

// cLeaf_s
enum : uint32_t { X_sizeof_cLeaf_s = 44, L_sizeof_cLeaf_s = 44 };
enum : uint32_t { X_cLeaf_s__firstCollAabbIndex = 0, L_cLeaf_s__firstCollAabbIndex = 0 };
enum : uint32_t { X_cLeaf_s__collAabbCount = 2, L_cLeaf_s__collAabbCount = 2 };
enum : uint32_t { X_cLeaf_s__brushContents = 4, L_cLeaf_s__brushContents = 4 };
enum : uint32_t { X_cLeaf_s__terrainContents = 8, L_cLeaf_s__terrainContents = 8 };
enum : uint32_t { X_cLeaf_s__mins = 12, L_cLeaf_s__mins = 12 };
enum : uint32_t { X_cLeaf_s__maxs = 24, L_cLeaf_s__maxs = 24 };
enum : uint32_t { X_cLeaf_s__leafBrushNode = 36, L_cLeaf_s__leafBrushNode = 36 };
enum : uint32_t { X_cLeaf_s__cluster = 40, L_cLeaf_s__cluster = 40 };
static const LayoutSpan SPANS_cLeaf_s[] = {{0,0,42}};

// cLeafBrushNode_s
enum : uint32_t { X_sizeof_cLeafBrushNode_s = 20, L_sizeof_cLeafBrushNode_s = 24 };
enum : uint32_t { X_cLeafBrushNode_s__axis = 0, L_cLeafBrushNode_s__axis = 0 };
enum : uint32_t { X_cLeafBrushNode_s__leafBrushCount = 2, L_cLeafBrushNode_s__leafBrushCount = 2 };
enum : uint32_t { X_cLeafBrushNode_s__contents = 4, L_cLeafBrushNode_s__contents = 4 };
enum : uint32_t { X_cLeafBrushNode_s__data = 8, L_cLeafBrushNode_s__data = 8, XN_cLeafBrushNode_s__data = 12, LN_cLeafBrushNode_s__data = 16 };
static const LayoutSpan SPANS_cLeafBrushNode_s[] = {{0,0,1},{2,2,6}};

// CollisionBorder
enum : uint32_t { X_sizeof_CollisionBorder = 28, L_sizeof_CollisionBorder = 28 };
enum : uint32_t { X_CollisionBorder__distEq = 0, L_CollisionBorder__distEq = 0 };
enum : uint32_t { X_CollisionBorder__zBase = 12, L_CollisionBorder__zBase = 12 };
enum : uint32_t { X_CollisionBorder__zSlope = 16, L_CollisionBorder__zSlope = 16 };
enum : uint32_t { X_CollisionBorder__start = 20, L_CollisionBorder__start = 20 };
enum : uint32_t { X_CollisionBorder__length = 24, L_CollisionBorder__length = 24 };
static const LayoutSpan SPANS_CollisionBorder[] = {{0,0,28}};

// CollisionPartition
enum : uint32_t { X_sizeof_CollisionPartition = 20, L_sizeof_CollisionPartition = 24 };
enum : uint32_t { X_CollisionPartition__triCount = 0, L_CollisionPartition__triCount = 0 };
enum : uint32_t { X_CollisionPartition__borderCount = 1, L_CollisionPartition__borderCount = 1 };
enum : uint32_t { X_CollisionPartition__firstTri = 4, L_CollisionPartition__firstTri = 4 };
enum : uint32_t { X_CollisionPartition__nuinds = 8, L_CollisionPartition__nuinds = 8 };
enum : uint32_t { X_CollisionPartition__fuind = 12, L_CollisionPartition__fuind = 12 };
enum : uint32_t { X_CollisionPartition__borders = 16, L_CollisionPartition__borders = 16 };
static const LayoutSpan SPANS_CollisionPartition[] = {{0,0,2},{4,4,12}};

// CollisionAabbTree
enum : uint32_t { X_sizeof_CollisionAabbTree = 32, L_sizeof_CollisionAabbTree = 32 };
enum : uint32_t { X_CollisionAabbTree__origin = 0, L_CollisionAabbTree__origin = 0 };
enum : uint32_t { X_CollisionAabbTree__materialIndex = 12, L_CollisionAabbTree__materialIndex = 12 };
enum : uint32_t { X_CollisionAabbTree__childCount = 14, L_CollisionAabbTree__childCount = 14 };
enum : uint32_t { X_CollisionAabbTree__halfSize = 16, L_CollisionAabbTree__halfSize = 16 };
enum : uint32_t { X_CollisionAabbTree__u = 28, L_CollisionAabbTree__u = 28 };
static const LayoutSpan SPANS_CollisionAabbTree[] = {{0,0,32}};

// cmodel_t
enum : uint32_t { X_sizeof_cmodel_t = 72, L_sizeof_cmodel_t = 72 };
enum : uint32_t { X_cmodel_t__mins = 0, L_cmodel_t__mins = 0 };
enum : uint32_t { X_cmodel_t__maxs = 12, L_cmodel_t__maxs = 12 };
enum : uint32_t { X_cmodel_t__radius = 24, L_cmodel_t__radius = 24 };
enum : uint32_t { X_cmodel_t__leaf__firstCollAabbIndex = 28, L_cmodel_t__leaf__firstCollAabbIndex = 28 };
enum : uint32_t { X_cmodel_t__leaf__collAabbCount = 30, L_cmodel_t__leaf__collAabbCount = 30 };
enum : uint32_t { X_cmodel_t__leaf__brushContents = 32, L_cmodel_t__leaf__brushContents = 32 };
enum : uint32_t { X_cmodel_t__leaf__terrainContents = 36, L_cmodel_t__leaf__terrainContents = 36 };
enum : uint32_t { X_cmodel_t__leaf__mins = 40, L_cmodel_t__leaf__mins = 40 };
enum : uint32_t { X_cmodel_t__leaf__maxs = 52, L_cmodel_t__leaf__maxs = 52 };
enum : uint32_t { X_cmodel_t__leaf__leafBrushNode = 64, L_cmodel_t__leaf__leafBrushNode = 64 };
enum : uint32_t { X_cmodel_t__leaf__cluster = 68, L_cmodel_t__leaf__cluster = 68 };
static const LayoutSpan SPANS_cmodel_t[] = {{0,0,70}};

// cbrush_t
enum : uint32_t { X_sizeof_cbrush_t = 96, L_sizeof_cbrush_t = 104 };
enum : uint32_t { X_cbrush_t__mins = 0, L_cbrush_t__mins = 0 };
enum : uint32_t { X_cbrush_t__contents = 12, L_cbrush_t__contents = 12 };
enum : uint32_t { X_cbrush_t__maxs = 16, L_cbrush_t__maxs = 16 };
enum : uint32_t { X_cbrush_t__numsides = 28, L_cbrush_t__numsides = 28 };
enum : uint32_t { X_cbrush_t__sides = 32, L_cbrush_t__sides = 32 };
enum : uint32_t { X_cbrush_t__axial_cflags = 36, L_cbrush_t__axial_cflags = 40 };
enum : uint32_t { X_cbrush_t__axial_sflags = 60, L_cbrush_t__axial_sflags = 64 };
enum : uint32_t { X_cbrush_t__numverts = 84, L_cbrush_t__numverts = 88 };
enum : uint32_t { X_cbrush_t__verts = 88, L_cbrush_t__verts = 96 };
static const LayoutSpan SPANS_cbrush_t[] = {{0,0,32},{36,40,52}};

// MapEnts
enum : uint32_t { X_sizeof_MapEnts = 12, L_sizeof_MapEnts = 24 };
enum : uint32_t { X_MapEnts__name = 0, L_MapEnts__name = 0 };
enum : uint32_t { X_MapEnts__entityString = 4, L_MapEnts__entityString = 8 };
enum : uint32_t { X_MapEnts__numEntityChars = 8, L_MapEnts__numEntityChars = 16 };
static const LayoutSpan SPANS_MapEnts[] = {{8,16,4}};

// DynEntityDef
enum : uint32_t { X_sizeof_DynEntityDef = 84, L_sizeof_DynEntityDef = 112 };
enum : uint32_t { X_DynEntityDef__type = 0, L_DynEntityDef__type = 0 };
enum : uint32_t { X_DynEntityDef__pose = 4, L_DynEntityDef__pose = 4 };
enum : uint32_t { X_DynEntityDef__xModel = 32, L_DynEntityDef__xModel = 32 };
enum : uint32_t { X_DynEntityDef__destroyedxModel = 36, L_DynEntityDef__destroyedxModel = 40 };
enum : uint32_t { X_DynEntityDef__brushModel = 40, L_DynEntityDef__brushModel = 48 };
enum : uint32_t { X_DynEntityDef__physicsBrushModel = 42, L_DynEntityDef__physicsBrushModel = 50 };
enum : uint32_t { X_DynEntityDef__destroyFx = 44, L_DynEntityDef__destroyFx = 56 };
enum : uint32_t { X_DynEntityDef__destroySound = 48, L_DynEntityDef__destroySound = 64 };
enum : uint32_t { X_DynEntityDef__destroyPieces = 52, L_DynEntityDef__destroyPieces = 72 };
enum : uint32_t { X_DynEntityDef__physPreset = 56, L_DynEntityDef__physPreset = 80 };
enum : uint32_t { X_DynEntityDef__physConstraints = 60, L_DynEntityDef__physConstraints = 88 };
enum : uint32_t { X_DynEntityDef__health = 68, L_DynEntityDef__health = 96 };
enum : uint32_t { X_DynEntityDef__flags = 72, L_DynEntityDef__flags = 100 };
enum : uint32_t { X_DynEntityDef__contents = 76, L_DynEntityDef__contents = 104 };
enum : uint32_t { X_DynEntityDef__targetname = 80, L_DynEntityDef__targetname = 108 };
enum : uint32_t { X_DynEntityDef__target = 82, L_DynEntityDef__target = 110 };
static const LayoutSpan SPANS_DynEntityDef[] = {{0,0,32},{40,48,4},{48,64,4},{60,88,24}};

// DynEntityPose
enum : uint32_t { X_sizeof_DynEntityPose = 32, L_sizeof_DynEntityPose = 32 };
enum : uint32_t { X_DynEntityPose__pose = 0, L_DynEntityPose__pose = 0 };
enum : uint32_t { X_DynEntityPose__radius = 28, L_DynEntityPose__radius = 28 };
static const LayoutSpan SPANS_DynEntityPose[] = {{0,0,32}};

// DynEntityClient
enum : uint32_t { X_sizeof_DynEntityClient = 20, L_sizeof_DynEntityClient = 20 };
enum : uint32_t { X_DynEntityClient__physObjId = 0, L_DynEntityClient__physObjId = 0 };
enum : uint32_t { X_DynEntityClient__flags = 4, L_DynEntityClient__flags = 4 };
enum : uint32_t { X_DynEntityClient__lightingHandle = 6, L_DynEntityClient__lightingHandle = 6 };
enum : uint32_t { X_DynEntityClient__health = 8, L_DynEntityClient__health = 8 };
enum : uint32_t { X_DynEntityClient__burnTime = 12, L_DynEntityClient__burnTime = 12 };
enum : uint32_t { X_DynEntityClient__fadeTime = 14, L_DynEntityClient__fadeTime = 14 };
enum : uint32_t { X_DynEntityClient__physicsStartTime = 16, L_DynEntityClient__physicsStartTime = 16 };
static const LayoutSpan SPANS_DynEntityClient[] = {{0,0,20}};

// DynEntityServer
enum : uint32_t { X_sizeof_DynEntityServer = 8, L_sizeof_DynEntityServer = 8 };
enum : uint32_t { X_DynEntityServer__flags = 0, L_DynEntityServer__flags = 0 };
enum : uint32_t { X_DynEntityServer__health = 4, L_DynEntityServer__health = 4 };
static const LayoutSpan SPANS_DynEntityServer[] = {{0,0,2},{4,4,4}};

// DynEntityColl
enum : uint32_t { X_sizeof_DynEntityColl = 32, L_sizeof_DynEntityColl = 32 };
enum : uint32_t { X_DynEntityColl__sector = 0, L_DynEntityColl__sector = 0 };
enum : uint32_t { X_DynEntityColl__nextEntInSector = 2, L_DynEntityColl__nextEntInSector = 2 };
enum : uint32_t { X_DynEntityColl__linkMins = 4, L_DynEntityColl__linkMins = 4 };
enum : uint32_t { X_DynEntityColl__linkMaxs = 16, L_DynEntityColl__linkMaxs = 16 };
enum : uint32_t { X_DynEntityColl__contents = 28, L_DynEntityColl__contents = 28 };
static const LayoutSpan SPANS_DynEntityColl[] = {{0,0,32}};

// PhysConstraint
enum : uint32_t { X_sizeof_PhysConstraint = 168, L_sizeof_PhysConstraint = 192 };
enum : uint32_t { X_PhysConstraint__targetname = 0, L_PhysConstraint__targetname = 0 };
enum : uint32_t { X_PhysConstraint__type = 4, L_PhysConstraint__type = 4 };
enum : uint32_t { X_PhysConstraint__attach_point_type1 = 8, L_PhysConstraint__attach_point_type1 = 8 };
enum : uint32_t { X_PhysConstraint__target_index1 = 12, L_PhysConstraint__target_index1 = 12 };
enum : uint32_t { X_PhysConstraint__target_ent1 = 16, L_PhysConstraint__target_ent1 = 16 };
enum : uint32_t { X_PhysConstraint__target_bone1 = 20, L_PhysConstraint__target_bone1 = 24 };
enum : uint32_t { X_PhysConstraint__attach_point_type2 = 24, L_PhysConstraint__attach_point_type2 = 32 };
enum : uint32_t { X_PhysConstraint__target_index2 = 28, L_PhysConstraint__target_index2 = 36 };
enum : uint32_t { X_PhysConstraint__target_ent2 = 32, L_PhysConstraint__target_ent2 = 40 };
enum : uint32_t { X_PhysConstraint__target_bone2 = 36, L_PhysConstraint__target_bone2 = 48 };
enum : uint32_t { X_PhysConstraint__offset = 40, L_PhysConstraint__offset = 56 };
enum : uint32_t { X_PhysConstraint__pos = 52, L_PhysConstraint__pos = 68 };
enum : uint32_t { X_PhysConstraint__pos2 = 64, L_PhysConstraint__pos2 = 80 };
enum : uint32_t { X_PhysConstraint__dir = 76, L_PhysConstraint__dir = 92 };
enum : uint32_t { X_PhysConstraint__flags = 88, L_PhysConstraint__flags = 104 };
enum : uint32_t { X_PhysConstraint__timeout = 92, L_PhysConstraint__timeout = 108 };
enum : uint32_t { X_PhysConstraint__min_health = 96, L_PhysConstraint__min_health = 112 };
enum : uint32_t { X_PhysConstraint__max_health = 100, L_PhysConstraint__max_health = 116 };
enum : uint32_t { X_PhysConstraint__distance = 104, L_PhysConstraint__distance = 120 };
enum : uint32_t { X_PhysConstraint__damp = 108, L_PhysConstraint__damp = 124 };
enum : uint32_t { X_PhysConstraint__power = 112, L_PhysConstraint__power = 128 };
enum : uint32_t { X_PhysConstraint__scale = 116, L_PhysConstraint__scale = 132 };
enum : uint32_t { X_PhysConstraint__spin_scale = 128, L_PhysConstraint__spin_scale = 144 };
enum : uint32_t { X_PhysConstraint__minAngle = 132, L_PhysConstraint__minAngle = 148 };
enum : uint32_t { X_PhysConstraint__maxAngle = 136, L_PhysConstraint__maxAngle = 152 };
enum : uint32_t { X_PhysConstraint__material = 140, L_PhysConstraint__material = 160 };
enum : uint32_t { X_PhysConstraint__constraintHandle = 144, L_PhysConstraint__constraintHandle = 168 };
enum : uint32_t { X_PhysConstraint__rope_index = 148, L_PhysConstraint__rope_index = 172 };
enum : uint32_t { X_PhysConstraint__centity_num = 152, L_PhysConstraint__centity_num = 176 };
static const LayoutSpan SPANS_PhysConstraint[] = {{0,0,2},{4,4,14},{24,32,10},{40,56,100},{144,168,24}};

// rope_t
enum : uint32_t { X_sizeof_rope_t = 3188, L_sizeof_rope_t = 3192 };
enum : uint32_t { X_rope_t__m_particles = 0, L_rope_t__m_particles = 0 };
enum : uint32_t { X_rope_t__m_constraints = 1000, L_rope_t__m_constraints = 1000 };
enum : uint32_t { X_rope_t__m_entity_anchors = 1840, L_rope_t__m_entity_anchors = 1840 };
enum : uint32_t { X_rope_t__m_num_particles = 1852, L_rope_t__m_num_particles = 1852 };
enum : uint32_t { X_rope_t__m_num_constraints = 1856, L_rope_t__m_num_constraints = 1856 };
enum : uint32_t { X_rope_t__m_num_entity_anchors = 1860, L_rope_t__m_num_entity_anchors = 1860 };
enum : uint32_t { X_rope_t__m_num_draw_verts = 1864, L_rope_t__m_num_draw_verts = 1864 };
enum : uint32_t { X_rope_t__m_client_verts = 1868, L_rope_t__m_client_verts = 1868 };
enum : uint32_t { X_rope_t__m_min = 3080, L_rope_t__m_min = 3080 };
enum : uint32_t { X_rope_t__m_max = 3092, L_rope_t__m_max = 3092 };
enum : uint32_t { X_rope_t__m_start = 3104, L_rope_t__m_start = 3104 };
enum : uint32_t { X_rope_t__m_end = 3116, L_rope_t__m_end = 3116 };
enum : uint32_t { X_rope_t__m_in_use = 3128, L_rope_t__m_in_use = 3128 };
enum : uint32_t { X_rope_t__m_visible = 3132, L_rope_t__m_visible = 3132 };
enum : uint32_t { X_rope_t__m_dist_constraint = 3136, L_rope_t__m_dist_constraint = 3136 };
enum : uint32_t { X_rope_t__m_flags = 3140, L_rope_t__m_flags = 3140 };
enum : uint32_t { X_rope_t__m_material = 3144, L_rope_t__m_material = 3144 };
enum : uint32_t { X_rope_t__m_seglen = 3148, L_rope_t__m_seglen = 3152 };
enum : uint32_t { X_rope_t__m_length = 3152, L_rope_t__m_length = 3156 };
enum : uint32_t { X_rope_t__m_width = 3156, L_rope_t__m_width = 3160 };
enum : uint32_t { X_rope_t__m_scale = 3160, L_rope_t__m_scale = 3164 };
enum : uint32_t { X_rope_t__m_force_scale = 3164, L_rope_t__m_force_scale = 3168 };
enum : uint32_t { X_rope_t__m_health = 3168, L_rope_t__m_health = 3172 };
enum : uint32_t { X_rope_t__m_frame = 3172, L_rope_t__m_frame = 3176 };
enum : uint32_t { X_rope_t__m_stable_count = 3176, L_rope_t__m_stable_count = 3180 };
enum : uint32_t { X_rope_t__m_static_rope = 3180, L_rope_t__m_static_rope = 3184 };
enum : uint32_t { X_rope_t__m_lightingHandle = 3184, L_rope_t__m_lightingHandle = 3188 };
static const LayoutSpan SPANS_rope_t[] = {{0,0,3144},{3148,3152,38}};

// XModelPieces
enum : uint32_t { X_sizeof_XModelPieces = 12, L_sizeof_XModelPieces = 24 };
enum : uint32_t { X_XModelPieces__name = 0, L_XModelPieces__name = 0 };
enum : uint32_t { X_XModelPieces__numpieces = 4, L_XModelPieces__numpieces = 8 };
enum : uint32_t { X_XModelPieces__pieces = 8, L_XModelPieces__pieces = 16 };
static const LayoutSpan SPANS_XModelPieces[] = {{4,8,4}};

// XModelPiece
enum : uint32_t { X_sizeof_XModelPiece = 16, L_sizeof_XModelPiece = 24 };
enum : uint32_t { X_XModelPiece__model = 0, L_XModelPiece__model = 0 };
enum : uint32_t { X_XModelPiece__offset = 4, L_XModelPiece__offset = 8 };
static const LayoutSpan SPANS_XModelPiece[] = {{4,8,12}};

// Glasses
enum : uint32_t { X_sizeof_Glasses = 56, L_sizeof_Glasses = 72 };
enum : uint32_t { X_Glasses__name = 0, L_Glasses__name = 0 };
enum : uint32_t { X_Glasses__numGlasses = 4, L_Glasses__numGlasses = 8 };
enum : uint32_t { X_Glasses__glasses = 8, L_Glasses__glasses = 16 };
enum : uint32_t { X_Glasses__workMemory = 12, L_Glasses__workMemory = 24 };
enum : uint32_t { X_Glasses__workMemorySize = 16, L_Glasses__workMemorySize = 32 };
enum : uint32_t { X_Glasses__smallAllocatorBlocks = 20, L_Glasses__smallAllocatorBlocks = 36 };
enum : uint32_t { X_Glasses__maxGroups = 24, L_Glasses__maxGroups = 40 };
enum : uint32_t { X_Glasses__maxShards = 28, L_Glasses__maxShards = 44 };
enum : uint32_t { X_Glasses__maxPhysics = 32, L_Glasses__maxPhysics = 48 };
enum : uint32_t { X_Glasses__shardMemorySize = 36, L_Glasses__shardMemorySize = 52 };
enum : uint32_t { X_Glasses__maxFreeCmd = 40, L_Glasses__maxFreeCmd = 56 };
enum : uint32_t { X_Glasses__numSlots = 44, L_Glasses__numSlots = 60 };
enum : uint32_t { X_Glasses__numVerts = 48, L_Glasses__numVerts = 64 };
enum : uint32_t { X_Glasses__numIndices = 52, L_Glasses__numIndices = 68 };
static const LayoutSpan SPANS_Glasses[] = {{4,8,4},{16,32,40}};

// Glass
enum : uint32_t { X_sizeof_Glass = 124, L_sizeof_Glass = 136 };
enum : uint32_t { X_Glass__glassDef = 0, L_Glass__glassDef = 0 };
enum : uint32_t { X_Glass__index = 4, L_Glass__index = 8 };
enum : uint32_t { X_Glass__brushModel = 8, L_Glass__brushModel = 12 };
enum : uint32_t { X_Glass__origin = 12, L_Glass__origin = 16 };
enum : uint32_t { X_Glass__angles = 24, L_Glass__angles = 28 };
enum : uint32_t { X_Glass__absmin = 36, L_Glass__absmin = 40 };
enum : uint32_t { X_Glass__absmax = 48, L_Glass__absmax = 52 };
enum : uint32_t { X_Glass__isPlanar = 60, L_Glass__isPlanar = 64 };
enum : uint32_t { X_Glass__numOutlineVerts = 61, L_Glass__numOutlineVerts = 65 };
enum : uint32_t { X_Glass__outline = 64, L_Glass__outline = 72 };
enum : uint32_t { X_Glass__outlineAxis = 68, L_Glass__outlineAxis = 80 };
enum : uint32_t { X_Glass__outlineOrigin = 104, L_Glass__outlineOrigin = 116 };
enum : uint32_t { X_Glass__uvScale = 116, L_Glass__uvScale = 128 };
enum : uint32_t { X_Glass__thickness = 120, L_Glass__thickness = 132 };
static const LayoutSpan SPANS_Glass[] = {{4,8,58},{68,80,56}};

// GlassDef
enum : uint32_t { X_sizeof_GlassDef = 60, L_sizeof_GlassDef = 96 };
enum : uint32_t { X_GlassDef__name = 0, L_GlassDef__name = 0 };
enum : uint32_t { X_GlassDef__maxHealth = 4, L_GlassDef__maxHealth = 8 };
enum : uint32_t { X_GlassDef__thickness = 8, L_GlassDef__thickness = 12 };
enum : uint32_t { X_GlassDef__minShardSize = 12, L_GlassDef__minShardSize = 16 };
enum : uint32_t { X_GlassDef__maxShardSize = 16, L_GlassDef__maxShardSize = 20 };
enum : uint32_t { X_GlassDef__shardLifeProbablility = 20, L_GlassDef__shardLifeProbablility = 24 };
enum : uint32_t { X_GlassDef__maxShards = 24, L_GlassDef__maxShards = 28 };
enum : uint32_t { X_GlassDef__pristineMaterial = 28, L_GlassDef__pristineMaterial = 32 };
enum : uint32_t { X_GlassDef__crackedMaterial = 32, L_GlassDef__crackedMaterial = 40 };
enum : uint32_t { X_GlassDef__shardMaterial = 36, L_GlassDef__shardMaterial = 48 };
enum : uint32_t { X_GlassDef__crackSound = 40, L_GlassDef__crackSound = 56 };
enum : uint32_t { X_GlassDef__shatterShound = 44, L_GlassDef__shatterShound = 64 };
enum : uint32_t { X_GlassDef__autoShatterShound = 48, L_GlassDef__autoShatterShound = 72 };
enum : uint32_t { X_GlassDef__crackEffect = 52, L_GlassDef__crackEffect = 80 };
enum : uint32_t { X_GlassDef__shatterEffect = 56, L_GlassDef__shatterEffect = 88 };
static const LayoutSpan SPANS_GlassDef[] = {{4,8,24}};

